UM Manager Java API: umm.api.NameValue Class Reference
umm.api.NameValue Class Reference
Public Member Functions
NameValue (String name, int value, String toolTip)
NameValue (String name, int value)
NameValue (String name)
String getName ()
void setName (String name)
int getValue ()
void setValue (int value)
String getToolTip ()
void setToolTip (String toolTip)
String toString ()
boolean equals (Object obj)
Detailed Description
Author
Stan
Member Function Documentation
String umm.api.NameValue.getName ()
Returns
the name
Referenced by umm.api.UMMAPI.getError(), umm.api.UMMAPI.saveApplication(), umm.api.UMMAPI.saveTemplate(), and umm.api.UMMAPI.setTemplates().
void umm.api.NameValue.setName (String name)
Parameters
name the name to set
void umm.api.NameValue.setToolTip (String toolTip)
Parameters
toolTip the tooltip to set
void umm.api.NameValue.setValue (int value)
Parameters
value the value to set
Referenced by umm.api.UMMAPI.saveUser().
The documentation for this class was generated from the following file:
NameValue.java