UM Manager Java API: umm.api.User Class Reference
umm.api.User Class Reference
Public Member Functions
User (String name)
String getUserName ()
void setUserName (String userName)
String getPassword ()
void setPassword (String password)
int getUserType ()
void setUserType (int type)
String getTypeStr ()
int getActive ()
boolean isActive ()
void setActive (boolean active)
void setActive (int a)
boolean compare (User user)
int getId ()
void setId (int id)
Static Public Attributes
static final String NORMAL_STR = "Normal"
static final String ADMIN_STR = "Admin"
static final int NORMAL = 0
static final int ADMIN = 1
Detailed Description
Author
Stan
Member Function Documentation
String umm.api.User.getPassword ()
Returns
The password. A User object retrieved with getUser() will have an encrypted (i.e., unreadable) password.
String umm.api.User.getUserName ()
Returns
the userName
int umm.api.User.getUserType ()
Returns
the type
Referenced by umm.api.UMMAPI.getConfig(), and umm.api.UMMAPI.setAdmin().
boolean umm.api.User.isActive ()
Returns
the active
void umm.api.User.setActive (boolean active)
Parameters
active the active to set
void umm.api.User.setId (int id)
Parameters
id the id to set
void umm.api.User.setPassword (String password)
Parameters
password the password to set
void umm.api.User.setUserName (String userName)
Parameters
userName the userName to set
void umm.api.User.setUserType (int type)
Parameters
type the type to set
Referenced by umm.api.UMMAPI.setAdmin().
The documentation for this class was generated from the following file:
User.java