UM Java API: com.latencybusters.lbm.UMQSourceEventMessageIdInfo Class Reference
com.latencybusters.lbm.UMQSourceEventMessageIdInfo Class Reference
Public Member Functions
UMQSourceEventMessageIdInfo (int flags, UMQMessageId msgId, Object clientObject) throws LBMEInvalException
int flags ()
UMQMessageId messageId ()
Object clientObject ()
Detailed Description
This class encapsulates information about a message sent to a queue. An object of type UMQSourceEventMessageIdInfo will be delivered with a source event of type LBM.SRC_EVENT_UMQ_MESSAGE_ID_INFO to notify the application of the message id that has been assigned to the message by the queue.
Since
UME 3.0
Constructor & Destructor Documentation
com.latencybusters.lbm.UMQSourceEventMessageIdInfo.UMQSourceEventMessageIdInfo (int flags, UMQMessageId msgId, Object clientObject) throws LBMEInvalException
Creates a UMQSourceEventMessageIdInfo object and initializes fields to the supplied values.
Exceptions
LBMEInvalException An invalid parameter was specified.
Since
UME 3.0
References com.latencybusters.lbm.UMQSourceEventMessageIdInfo.clientObject(), and com.latencybusters.lbm.UMQSourceEventMessageIdInfo.flags().
Member Function Documentation
Object com.latencybusters.lbm.UMQSourceEventMessageIdInfo.clientObject ()
Get the client object provided when the message was sent.
Returns
The object provided when sending the message associated with this message info.
Since
UME 3.0
References com.latencybusters.lbm.UMQSourceEventMessageIdInfo.flags().
Referenced by com.latencybusters.lbm.UMQSourceEventMessageIdInfo.UMQSourceEventMessageIdInfo().
int com.latencybusters.lbm.UMQSourceEventMessageIdInfo.flags ()
Get informational flags for this info object.
Returns
Flags.
Since
UME 3.0
Referenced by com.latencybusters.lbm.UMQSourceEventMessageIdInfo.clientObject(), and com.latencybusters.lbm.UMQSourceEventMessageIdInfo.UMQSourceEventMessageIdInfo().
UMQMessageId com.latencybusters.lbm.UMQSourceEventMessageIdInfo.messageId ()
Get the message Id object identifying the message.
Returns
A UMQMessageId object identifying the message.
Since
UME 3.0
The documentation for this class was generated from the following file:
UMQSourceEventMessageIdInfo.java