UM Java API: com.latencybusters.lbm.sdm.LBMSDM Class Reference
com.latencybusters.lbm.sdm.LBMSDM Class Reference
Class LBMSDM is the parent class from which the core SDM functionality derives. See Self Describing Messaging for general information on SDM.
Public Member Functions
void set_debug_level (int level)
void log (String s)
Static Public Attributes
static final int DEBUG_BASIC = 1
static final int DEBUG_VERBOSE_PARSING = 2
Protected Attributes
int debug_level = 0
Detailed Description
Class LBMSDM is the parent class from which the core SDM functionality derives. See Self Describing Messaging for general information on SDM.
Member Function Documentation
void com.latencybusters.lbm.sdm.LBMSDM.log (String s)
Log an event. If debug level is set greater than 0, output to stderr
Referenced by com.latencybusters.lbm.sdm.LBMSDMFields.get_attr(), com.latencybusters.lbm.sdm.LBMSDMFields.LBMSDMFields(), com.latencybusters.lbm.sdm.LBMSDMFieldBlob.set(), com.latencybusters.lbm.sdm.LBMSDMFieldMessage.set(), com.latencybusters.lbm.sdm.LBMSDMFieldDecimal.set(), com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp.set(), com.latencybusters.lbm.sdm.LBMSDMArrayDecimal.set(), and com.latencybusters.lbm.sdm.LBMSDMArrayUint64.set().
void com.latencybusters.lbm.sdm.LBMSDM.set_debug_level (int level)
Set the debug level for processing this SDM message. Currently all debugs go to standard out.
Member Data Documentation
final int com.latencybusters.lbm.sdm.LBMSDM.DEBUG_BASIC = 1 static
Debug flag for basic debug output
int com.latencybusters.lbm.sdm.LBMSDM.debug_level = 0 protected
Debug mask for SDM implementation.
See also
set_debug_level
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data(), com.latencybusters.lbm.sdm.LBMSDMessage.parse(), com.latencybusters.lbm.sdm.LBMSDMFieldMessage.parse(), and com.latencybusters.lbm.sdm.LBMSDMArrayMessage.parse().
final int com.latencybusters.lbm.sdm.LBMSDM.DEBUG_VERBOSE_PARSING = 2 static
Debug flag for verbose message parsing output
The documentation for this class was generated from the following file:
LBMSDM.java