UM Java API: com.latencybusters.lbm.UMQSourceEventULBReceiverInfo Class Reference
com.latencybusters.lbm.UMQSourceEventULBReceiverInfo Class Reference
Public Member Functions
UMQSourceEventULBReceiverInfo (int flags, long regId, long assignId, long appSetIdx, String receiver) throws LBMEInvalException
int flags ()
long registrationId ()
long assignmentId ()
long applicationSetIndex ()
String receiver ()
Detailed Description
UMQ ULB Receiver Info class. This info object is both delivered with a source event and acts as a base class for other ULB source events. In both cases, this object holds information about a ULB receiver.
Since
UMQ 1.1
Constructor & Destructor Documentation
com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.UMQSourceEventULBReceiverInfo (int flags, long regId, long assignId, long appSetIdx, String receiver) throws LBMEInvalException
Creates a UMQSourceEventULBReceiverInfo object and initializes fields to the supplied values.
Parameters
flags Informational flags.
regId Registration ID of the receiver.
assignId The Assignment ID of the receiver.
appSetIdx The application set index the receiver is in.
receiver The receivers immediate message target string.
Exceptions
LBMEInvalException An invalid parameter was specified.
Since
UMQ 1.1
References com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.flags(), and com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.receiver().
Member Function Documentation
long com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.applicationSetIndex ()
Get Application Set index for the receiver associated with this info object.
Returns
Application Set index for the receiver associated with this info object.
Since
UMQ 1.1
long com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.assignmentId ()
Get Assignment ID for the receiver associated with this info object.
Returns
Assignment ID of the receiver associated with this info object.
Since
UMQ 1.1
int com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.flags ()
Get informational flags for this info object.
Returns
Flags.
Since
UMQ 1.1
Referenced by com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.receiver(), com.latencybusters.lbm.UMQSourceEventULBMessageInfo.UMQSourceEventULBMessageInfo(), and com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.UMQSourceEventULBReceiverInfo().
String com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.receiver ()
Get immediate message target string for the receiver associated with this info object.
Returns
Immediate message target string for the receiver associated with this info object.
Since
UMQ 1.1
References com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.flags().
Referenced by com.latencybusters.lbm.UMQSourceEventULBMessageInfo.UMQSourceEventULBMessageInfo(), and com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.UMQSourceEventULBReceiverInfo().
long com.latencybusters.lbm.UMQSourceEventULBReceiverInfo.registrationId ()
Get Registration ID for the receiver associated with this info object.
Returns
Registration ID of the receiver associated with this info object.
Since
UMQ 1.1
The documentation for this class was generated from the following file:
UMQSourceEventULBReceiverInfo.java