UM Java API: com.latencybusters.lbm.LBMAuthUserInfo Class Reference
com.latencybusters.lbm.LBMAuthUserInfo Class Reference
Public Member Functions
LBMAuthUserInfo (String username, String password)
String username ()
String password ()
void setUsername (String username)
void setPassword (String password)
Detailed Description
Class containing the user information (username and password) for authentication purposes.
Member Function Documentation
String com.latencybusters.lbm.LBMAuthUserInfo.password ()
Returns the password.
Returns
password.
Referenced by com.latencybusters.lbm.LBMAuthUserInfo.setPassword().
void com.latencybusters.lbm.LBMAuthUserInfo.setPassword (String password)
Sets password.
Parameters
password to set.
References com.latencybusters.lbm.LBMAuthUserInfo.password().
void com.latencybusters.lbm.LBMAuthUserInfo.setUsername (String username)
Sets username.
Parameters
username to set.
References com.latencybusters.lbm.LBMAuthUserInfo.username().
String com.latencybusters.lbm.LBMAuthUserInfo.username ()
Returns the user name.
Returns
username.
Referenced by com.latencybusters.lbm.LBMAuthUserInfo.setUsername().
The documentation for this class was generated from the following file:
LBMAuthUserInfo.java