UM Java API: com.latencybusters.lbm.UMERegistrationSuccessInfo Class Reference
com.latencybusters.lbm.UMERegistrationSuccessInfo Class Reference
Public Member Functions
UMERegistrationSuccessInfo ()
UMERegistrationSuccessInfo (int flags, long sourceRegId, long receiverRegId, long sequenceNumber, int storeIndex, String store) throws LBMEInvalException
int flags ()
long sourceRegistrationId ()
long receiverRegistrationId ()
long sequenceNumber ()
int storeIndex ()
String store ()
long sourceSessionId ()
Detailed Description
UME Registration Success Info class. Contains extended information for UME registration success messages, like flags indicating any conditions on store registration, source and receiver registration IDs, and the store's name and group index.
Since
UME 2.0
Constructor & Destructor Documentation
com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo ()
Creates a UMERegistrationSuccessInfo object and initializes all fields to 0/null.
Referenced by com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo().
com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo (int flags, long sourceRegId, long receiverRegId, long sequenceNumber, int storeIndex, String store) throws LBMEInvalException
Creates a UMERegistrationSuccessInfo object and initializes fields to supplied values.
Parameters
flags Flags concerning the type of registration.
sourceRegId Source registration ID (must be >= 0).
receiverRegId Receiver registration ID (must be >= 0).
storeIndex Index of store registered with (must be >= 0).
store Name (IP address) of store registered with.
sequenceNumber The starting sequence number according to the store.
Exceptions
LBMEInvalException if sourceRegId, receiverRegId, or storeIndex are < 0.
Since
UME 2.0
Deprecated:
As of UMP 6.7, Made internal with no replacement. Applications do not need this constructor.
References com.latencybusters.lbm.UMERegistrationSuccessInfo.flags(), com.latencybusters.lbm.UMERegistrationSuccessInfo.sequenceNumber(), com.latencybusters.lbm.UMERegistrationSuccessInfo.store(), com.latencybusters.lbm.UMERegistrationSuccessInfo.storeIndex(), and com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo().
Member Function Documentation
int com.latencybusters.lbm.UMERegistrationSuccessInfo.flags ()
Get registration success flags.
Returns
Flags.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo().
long com.latencybusters.lbm.UMERegistrationSuccessInfo.receiverRegistrationId ()
Get receiver registration ID.
Returns
receiver registration ID.
Since
UME 2.0
long com.latencybusters.lbm.UMERegistrationSuccessInfo.sequenceNumber ()
Get starting sequence number.
Returns
starting sequence number.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo().
long com.latencybusters.lbm.UMERegistrationSuccessInfo.sourceRegistrationId ()
Get source registration ID.
Returns
source registration ID.
Since
UME 2.0
long com.latencybusters.lbm.UMERegistrationSuccessInfo.sourceSessionId ()
Get the sources session id if set. Note that the session id is an unsigned 64 bit value being represented here as signed.
Returns
The sources session id
Since
UMP 6.7
String com.latencybusters.lbm.UMERegistrationSuccessInfo.store ()
Get name (IP address) of the store successfully registered with.
Returns
Name (IP address) of the store.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo().
int com.latencybusters.lbm.UMERegistrationSuccessInfo.storeIndex ()
Get index of the store successfully registered with.
Returns
index of the store.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMERegistrationSuccessInfo.UMERegistrationSuccessInfo().
The documentation for this class was generated from the following file:
UMERegistrationSuccessInfo.java