UM Java API: com.latencybusters.lbm.UMERegistrationCompleteInfo Class Reference
com.latencybusters.lbm.UMERegistrationCompleteInfo Class Reference
Public Member Functions
UMERegistrationCompleteInfo ()
UMERegistrationCompleteInfo (int flags, long sequenceNumber) throws LBMEInvalException
UMERegistrationCompleteInfo (int flags, long sequenceNumber, long sid) throws LBMEInvalException
int flags ()
long sequenceNumber ()
long sourceSessionId ()
Detailed Description
UME Registration Complete Info class. Contains extended information for UME receiver registration complete messages.
Since
UME 2.0
Constructor & Destructor Documentation
com.latencybusters.lbm.UMERegistrationCompleteInfo.UMERegistrationCompleteInfo ()
Creates a UMERegistrationCompleteInfo object and initializes fields to 0.
com.latencybusters.lbm.UMERegistrationCompleteInfo.UMERegistrationCompleteInfo (int flags, long sequenceNumber) throws LBMEInvalException
Creates a UMERegistrationCompleteInfo object and initializes fields to the supplied values.
Parameters
flags Informational flags.
sequenceNumber Starting sequence number (must be >= 0).
Exceptions
LBMEInvalException if sequenceNumber < 0.
Since
UME 2.0
Deprecated:
As of UMP 6.7, Made internal with no replacement. Applications do not need this constructor.
References com.latencybusters.lbm.UMERegistrationCompleteInfo.flags(), and com.latencybusters.lbm.UMERegistrationCompleteInfo.sequenceNumber().
com.latencybusters.lbm.UMERegistrationCompleteInfo.UMERegistrationCompleteInfo (int flags, long sequenceNumber, long sid) throws LBMEInvalException
Creates a UMERegistrationCompleteInfo object and initializes fields to the supplied values.
Parameters
flags Informational flags.
sequenceNumber Starting sequence number (must be >= 0).
sid Source specified session ID.
Exceptions
LBMEInvalException if sequenceNumber < 0.
Since
UMP 6.7
References com.latencybusters.lbm.UMERegistrationCompleteInfo.flags(), and com.latencybusters.lbm.UMERegistrationCompleteInfo.sequenceNumber().
Member Function Documentation
int com.latencybusters.lbm.UMERegistrationCompleteInfo.flags ()
Get informational flags for this registration complete message.
Returns
Flags.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMERegistrationCompleteInfo.UMERegistrationCompleteInfo().
long com.latencybusters.lbm.UMERegistrationCompleteInfo.sequenceNumber ()
Get starting sequence number for this registration complete message.
Returns
Sequence number.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMERegistrationCompleteInfo.UMERegistrationCompleteInfo().
long com.latencybusters.lbm.UMERegistrationCompleteInfo.sourceSessionId ()
Get the sources session id. Note that the session id is an unsigned 64 bit value being represented here as a signed long.
Returns
The sources session id
Since
UMP 6.7
The documentation for this class was generated from the following file:
UMERegistrationCompleteInfo.java