UM Java API: com.latencybusters.lbm.sdm.LBMSDMRawUint32 Class Reference
com.latencybusters.lbm.sdm.LBMSDMRawUint32 Class Reference
Public Member Functions
void set (long v) throws LBMSDMException
LBMSDMRawUint32 () throws LBMSDMException
LBMSDMRawUint32 (long v) throws LBMSDMException
int format (byte[] buf, int offset) throws LBMSDMException
String toString ()
int parse (byte[] buf, int offset) throws LBMSDMException
long toLong ()
LBMSDMRawUint32 clone () throws CloneNotSupportedException
String toDbgString ()
void set_debug_level (int level)
void log (String s)
Static Public Member Functions
static int format (byte[] buf, int offset, long v) throws LBMSDMException
static long parse_s (byte[] buf, int offset) throws LBMSDMException
Static Public Attributes
static final int length = 4
static final int DEBUG_BASIC = 1
static final int DEBUG_VERBOSE_PARSING = 2
Protected Attributes
int debug_level = 0
Detailed Description
An LBMSDMRawUint32 is a helper class to minimise the effort of formatting and parsing unsigned 32 bit integers
Constructor & Destructor Documentation
com.latencybusters.lbm.sdm.LBMSDMRawUint32.LBMSDMRawUint32 () throws LBMSDMException
Create a raw uint32 field, defaulting to 0
Referenced by com.latencybusters.lbm.sdm.LBMSDMRawUint32.clone().
com.latencybusters.lbm.sdm.LBMSDMRawUint32.LBMSDMRawUint32 (long v) throws LBMSDMException
Set a raw uint16 field providing the value as a long
Parameters
v The long to seed this raw object
Exceptions
LBMSDMUnsignedException if an unsigned value is passed in
Member Function Documentation
LBMSDMRawUint32 com.latencybusters.lbm.sdm.LBMSDMRawUint32.clone () throws CloneNotSupportedException
Get a copy of this object
Returns
A copy of the uint64
References com.latencybusters.lbm.sdm.LBMSDMRawUint32.clone(), and com.latencybusters.lbm.sdm.LBMSDMRawUint32.LBMSDMRawUint32().
Referenced by com.latencybusters.lbm.sdm.LBMSDMRawUint32.clone(), and com.latencybusters.lbm.sdm.LBMSDMRawTimestamp.clone().
static int com.latencybusters.lbm.sdm.LBMSDMRawUint32.format (byte [] buf, int offset, long v) throws LBMSDMException static
Format a uint32 value into a byte buffer
Parameters
buf The buffer to contain the formatted value
offset The offset in to the buffer to start formatting
v The value of the uint32 to be formatted as a long
Returns
The offset after formatting the long
References com.latencybusters.lbm.sdm.LBMSDMRawUint32.length.
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data(), com.latencybusters.lbm.sdm.LBMSDMRawFloat.format(), com.latencybusters.lbm.sdm.LBMSDMRawUint32.format(), com.latencybusters.lbm.sdm.LBMSDMFieldString.format(), com.latencybusters.lbm.sdm.LBMSDMFieldUnicode.format(), com.latencybusters.lbm.sdm.LBMSDMFieldBlob.format(), and com.latencybusters.lbm.sdm.LBMSDMRawTimestamp.format().
int com.latencybusters.lbm.sdm.LBMSDMRawUint32.format (byte [] buf, int offset) throws LBMSDMException
Format the raw uint32 value into a byte buffer
Parameters
buf The buffer to contain the formatted value
offset The offset in to the buffer to start formatting
Returns
The offset after formatting this object
References com.latencybusters.lbm.sdm.LBMSDMRawUint32.format(), and com.latencybusters.lbm.sdm.LBMSDMRawUint32.length.
void com.latencybusters.lbm.sdm.LBMSDM.log (String s) inherited
Log an event. If debug level is set greater than 0, output to stderr
Referenced by com.latencybusters.lbm.sdm.LBMSDMFields.get_attr(), com.latencybusters.lbm.sdm.LBMSDMFields.LBMSDMFields(), com.latencybusters.lbm.sdm.LBMSDMFieldBlob.set(), com.latencybusters.lbm.sdm.LBMSDMFieldMessage.set(), com.latencybusters.lbm.sdm.LBMSDMFieldDecimal.set(), com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp.set(), com.latencybusters.lbm.sdm.LBMSDMArrayDecimal.set(), and com.latencybusters.lbm.sdm.LBMSDMArrayUint64.set().
int com.latencybusters.lbm.sdm.LBMSDMRawUint32.parse (byte [] buf, int offset) throws LBMSDMException
Parse the raw uint32 value from a byte buffer
Parameters
buf The buffer that contains the formatted value
offset The offset in to the buffer to start parsing
Returns
the new offset after parsing the field
References com.latencybusters.lbm.sdm.LBMSDMRawUint32.length, and com.latencybusters.lbm.sdm.LBMSDMRawUint32.toLong().
Referenced by com.latencybusters.lbm.sdm.LBMSDMRawTimestamp.parse().
static long com.latencybusters.lbm.sdm.LBMSDMRawUint32.parse_s (byte [] buf, int offset) throws LBMSDMException static
Parse the raw uint32 value from a byte buffer
Parameters
buf The buffer that contains the formatted value
offset The offset in to the buffer to start parsing
Returns
the new offset after parsing the field
References com.latencybusters.lbm.sdm.LBMSDMRawUint32.toLong().
Referenced by com.latencybusters.lbm.sdm.LBMSDMRawFloat.parse_s().
void com.latencybusters.lbm.sdm.LBMSDMRawUint32.set (long v) throws LBMSDMException
Set a uint32 field providing the value as a long
Parameters
v The long to seed this raw object
Exceptions
LBMSDMUnsignedException if an unsigned value is passed in
Referenced by com.latencybusters.lbm.sdm.LBMSDMRawTimestamp.set().
void com.latencybusters.lbm.sdm.LBMSDM.set_debug_level (int level) inherited
Set the debug level for processing this SDM message. Currently all debugs go to standard out.
String com.latencybusters.lbm.sdm.LBMSDMRaw.toDbgString () inherited
Get a debug string for this object. This is not expected to be called and exists for child classes.
Returns
returns null - derived classes override with their value
Referenced by com.latencybusters.lbm.sdm.LBMSDMBadRawObjectException.LBMSDMBadRawObjectException().
long com.latencybusters.lbm.sdm.LBMSDMRawUint32.toLong ()
Get the long representation of the uint32
Returns
A long with the value of the object
Referenced by com.latencybusters.lbm.sdm.LBMSDMRawUint32.parse(), com.latencybusters.lbm.sdm.LBMSDMRawUint32.parse_s(), and com.latencybusters.lbm.sdm.LBMSDMRawUint32.toString().
String com.latencybusters.lbm.sdm.LBMSDMRawUint32.toString ()
Get a string version of an uint16
Returns
A string representation of the uint16
References com.latencybusters.lbm.sdm.LBMSDMRawUint32.toLong().
Member Data Documentation
final int com.latencybusters.lbm.sdm.LBMSDM.DEBUG_BASIC = 1 static inherited
Debug flag for basic debug output
int com.latencybusters.lbm.sdm.LBMSDM.debug_level = 0 protected inherited
Debug mask for SDM implementation.
See also
set_debug_level
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data(), com.latencybusters.lbm.sdm.LBMSDMessage.parse(), com.latencybusters.lbm.sdm.LBMSDMFieldMessage.parse(), and com.latencybusters.lbm.sdm.LBMSDMArrayMessage.parse().
final int com.latencybusters.lbm.sdm.LBMSDM.DEBUG_VERBOSE_PARSING = 2 static inherited
Debug flag for verbose message parsing output
final int com.latencybusters.lbm.sdm.LBMSDMRawUint32.length = 4 static
The number of bytes needed to store a raw LBMSDMRawUint32
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data(), com.latencybusters.lbm.sdm.LBMSDMRawUint32.format(), com.latencybusters.lbm.sdm.LBMSDMFieldUnicode.format(), com.latencybusters.lbm.sdm.LBMSDMFieldBlob.get_len(), and com.latencybusters.lbm.sdm.LBMSDMRawUint32.parse().
The documentation for this class was generated from the following file:
LBMSDMRawUint32.java