UM Java API: com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo Class Reference
com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo Class Reference
Public Member Functions
UMESourceEventRegistrationCompleteInfo ()
UMESourceEventRegistrationCompleteInfo (int flags, long sequenceNumber) throws LBMEInvalException
int flags ()
long sequenceNumber ()
Detailed Description
UME Source Event Registration Complete Info class. Contains the starting sequence number for a source returned from a UME store.
Since
UME 2.0
Constructor & Destructor Documentation
com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.UMESourceEventRegistrationCompleteInfo ()
Creates a UMESourceEventRegistrationCompleteInfo object and initializes all fields to 0.
Since
UME 2.0
com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.UMESourceEventRegistrationCompleteInfo (int flags, long sequenceNumber) throws LBMEInvalException
Creates a UMESourcEventRegistrationCompleteInfo object and initializes fields to the supplied values.
Parameters
flags Informational flags.
sequenceNumber Starting sequence number (must be >= 0).
Exceptions
LBMEInvalException if sequenceNumber < 0.
Since
UME 2.0
References com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.flags(), and com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.sequenceNumber().
Member Function Documentation
int com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.flags ()
Get flags concerning this registration complete message.
Returns
Flags.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.sequenceNumber(), and com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.UMESourceEventRegistrationCompleteInfo().
long com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.sequenceNumber ()
Get the starting sequence number.
Returns
Sequence number.
References com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.flags().
Referenced by com.latencybusters.lbm.UMESourceEventRegistrationCompleteInfo.UMESourceEventRegistrationCompleteInfo().
The documentation for this class was generated from the following file:
UMESourceEventRegistrationCompleteInfo.java