UM Java API: com.latencybusters.lbm.LBMSourceEventFlightSizeNotification Class Reference
com.latencybusters.lbm.LBMSourceEventFlightSizeNotification Class Reference
Public Member Functions
LBMSourceEventFlightSizeNotification (int type, int state)
int type ()
int state ()
Detailed Description
LBM Source Event Flight Size Notification class. Contains type and state of current flight size
Since
UME 3.1
Constructor & Destructor Documentation
com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.LBMSourceEventFlightSizeNotification (int type, int state)
Creates an LBMSourceEventFlightSizeNotification with fields initialized to the given values.
Parameters
type type of flight size in question.
state current state (over or under).
Since
UME 3.1
References com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.state(), and com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.type().
Member Function Documentation
int com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.state ()
Get state.
Returns
state of flight size.
Since
UME 3.1
References com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.type().
Referenced by com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.LBMSourceEventFlightSizeNotification().
int com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.type ()
Get type.
Returns
type of flight size.
Since
UME 3.1
Referenced by com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.LBMSourceEventFlightSizeNotification(), and com.latencybusters.lbm.LBMSourceEventFlightSizeNotification.state().
The documentation for this class was generated from the following file:
LBMSourceEventFlightSizeNotification.java