UM Java API: com.latencybusters.lbm.LBMImmediateMessageSourceStatistics Class Reference
com.latencybusters.lbm.LBMImmediateMessageSourceStatistics Class Reference
Inherits com.latencybusters.lbm.LBMStatistics.
Public Member Functions
LBMImmediateMessageSourceStatistics ()
LBMImmediateMessageSourceStatistics (LBMContext lbmctx, int maxStats) throws LBMException
void refresh (LBMContext lbmctx, int maxStats) throws LBMException
void dispose ()
int size ()
int type () throws LBMException
int type (int n) throws LBMException
String typeName () throws LBMException
String typeName (int n) throws LBMException
String source () throws LBMException
String source (int n) throws LBMException
long numberOfClients () throws LBMException
long numberOfClients (int n) throws LBMException
long bytesBuffered () throws LBMException
long bytesBuffered (int n) throws LBMException
long messagesSent () throws LBMException
long messagesSent (int n) throws LBMException
long bytesSent () throws LBMException
long bytesSent (int n) throws LBMException
long transmissionWindowMessages () throws LBMException
long transmissionWindowMessages (int n) throws LBMException
long transmissionWindowBytes () throws LBMException
long transmissionWindowBytes (int n) throws LBMException
long nakPacketsReceived () throws LBMException
long nakPacketsReceived (int n) throws LBMException
long naksReceived () throws LBMException
long naksReceived (int n) throws LBMException
long naksIgnored () throws LBMException
long naksIgnored (int n) throws LBMException
long naksShed () throws LBMException
long naksShed (int n) throws LBMException
long naksIgnoredRetransmitDelay () throws LBMException
long naksIgnoredRetransmitDelay (int n) throws LBMException
long retransmissionsSent () throws LBMException
long retransmissionsSent (int n) throws LBMException
long messagesQueued () throws LBMException
long messagesQueued (int n) throws LBMException
long retransmissionsQueued () throws LBMException
long retransmissionsQueued (int n) throws LBMException
long retransmissionBytesSent () throws LBMException
long retransmissionBytesSent (int n) throws LBMException
String getApplicationSourceId ()
InetAddress getSender () throws UnknownHostException
Date getTimestamp ()
long getProcessId ()
long getContextId ()
Protected Member Functions
void finalize ()
void setSender (long ip)
void setTimestamp (long ts)
void setApplicationSourceId (String appid)
void setProcessId (long pid)
void setContextId (long cid)
Detailed Description
UM Immediate Message Sender statistics
This object provides user monitoring with access to statistics of an application being monitored. The user monitoring code can be part of the application being monitored (i.e. the application can be "self-monitoring"), or the monitoring code can be remote, using the lbmmon infrastructure to deliver statistics.
    Note that when stats are sampled, the fields in the structure are not
    necessarily from the same instant in time.  The structure might be
    updated concurrently with it being sampled, and while each structure
    field is atomically read, the field values can be skewed slightly
    across time.
Constructor & Destructor Documentation
com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.LBMImmediateMessageSourceStatistics ()
Instantiate an empty object containing no statistics.
com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.LBMImmediateMessageSourceStatistics (LBMContext lbmctx, int maxStats) throws LBMException
Instantiate object containing the aggregate set of statistics for a particular context. This constructor will throw LBMMonitorEInvalException if maxStats is less than the available number of transport statistical sets.
Parameters
lbmctx LBMContext object
maxStats Maximum number of sources
Exceptions
LBMException if any error occurred retrieving immediate message receiver statistics.
See also
refresh
References com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.refresh().
Member Function Documentation
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.bytesBuffered () throws LBMException
Number of bytes currently in UM's TCP buffer, i.e., a snapshot (TCP only). This count is affected by the number of receivers,and configuration options transport_tcp_multiple_receiver_behavior and transport_session_maximum_buffer. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of bytes currently in UM's TCP buffer
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.bytesBuffered (int n) throws LBMException
Number of bytes currently in UM's TCP buffer, i.e., a snapshot (TCP only). This count is affected by the number of receivers,and configuration options transport_tcp_multiple_receiver_behavior and transport_session_maximum_buffer. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of bytes currently in UM's TCP buffer
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.bytesSent () throws LBMException
Number of datagram bytes sent (LBT-RM only). This is the total of lengths of all LBT-RM packets, including UM header information. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of datagram bytes sent
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.bytesSent (int n) throws LBMException
Number of datagram bytes sent (LBT-RM only). This is the total of lengths of all LBT-RM packets, including UM header information. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of datagram bytes sent
Exceptions
LBMException if any error occurred retrieving source statistics.
void com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.dispose ()
Free memory associated with this set of statistics.
Referenced by com.latencybusters.lbm.LBMObjectRecycler.close(), and com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.finalize().
void com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.finalize () protected
This method is for internal use only, and is not supported for customer applications.
References com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.dispose().
String com.latencybusters.lbm.LBMStatistics.getApplicationSourceId () inherited
Retrieve the application source identifier associated with this set of statistics.
This attribute is only set for remote statistics returned by the lbmmon infrastructure. For locally-gathered statistics, this method returns an undefined value.
Returns
Application source ID
long com.latencybusters.lbm.LBMStatistics.getContextId () inherited
Retrieve the sending context ID associated with this set of statistics.
This attribute is only set for remote statistics returned by the lbmmon infrastructure. For locally-gathered statistics, this method returns an undefined value.
Returns
Context ID
long com.latencybusters.lbm.LBMStatistics.getProcessId () inherited
Retrieve the sending process ID associated with this set of statistics.
This attribute is only set for remote statistics returned by the lbmmon infrastructure. For locally-gathered statistics, this method returns an undefined value.
Returns
Process ID
InetAddress com.latencybusters.lbm.LBMStatistics.getSender () throws UnknownHostException inherited
Retrieve the IP sender address associated with this set of statistics.
This attribute is only set for remote statistics returned by the lbmmon infrastructure. For locally-gathered statistics, this method returns an undefined value.
Returns
InetAddress object corresponding to the statistics' sender IP address
Exceptions
UnknownHostException if IP address is of illegal length.
Date com.latencybusters.lbm.LBMStatistics.getTimestamp () inherited
Retrieve the timestamp associated with this set of statistics.
This attribute is only set for remote statistics returned by the lbmmon infrastructure. For locally-gathered statistics, this method returns an undefined value.
Returns
Timestamp Date object
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.messagesQueued () throws LBMException
Number of datagrams currently queued by the data rate limiter (LBT-RM only). When a source transport attempts to send messages (any type) faster than its data rate limiter allows (set by configuration option transport_lbtrm_data_rate_limit, default 10Mbps), the data rate limiter queues the messages until they can be sent within the data rate limit. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of datagrams currently queued by the data rate limiter
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.messagesQueued (int n) throws LBMException
Number of datagrams currently queued by the data rate limiter (LBT-RM only). When a source transport attempts to send messages (any type) faster than its data rate limiter allows (set by configuration option transport_lbtrm_data_rate_limit, default 10Mbps), the data rate limiter queues the messages until they can be sent within the data rate limit. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of datagrams currently queued by the data rate limiter
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.messagesSent () throws LBMException
Number of datagrams sent (LBT-RM only). Depending on batching settings, a single datagram may contain one or more messages, or a fragment of a larger message. With LBT-RM, larger messages are split into fragment sizes limited by configuration option transport_lbtrm_datagram_max_size (default 8KB). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of datagrams sent
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.messagesSent (int n) throws LBMException
Number of datagrams sent (LBT-RM only). Depending on batching settings, a single datagram may contain one or more messages, or a fragment of a larger message. With LBT-RM, larger messages are split into fragment sizes limited by configuration option transport_lbtrm_datagram_max_size (default 8KB). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of datagrams sent
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.nakPacketsReceived () throws LBMException
Number of NAK packets received by this source transport (LBT-RM only). UM batches NAKs into NAK packets to save network bandwidth. This should always be less than or equal to naksReceived (below). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of NAK packets received by this source transport
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.nakPacketsReceived (int n) throws LBMException
Number of NAK packets received by this source transport (LBT-RM only). UM batches NAKs into NAK packets to save network bandwidth. This should always be less than or equal to naksReceived (below). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of NAK packets received by this source transport
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksIgnored () throws LBMException
Number of NAKs the source ignored and sent an NCF with reason code "ignored" (LBT-RM only). A source transport ignores a NAK for a datagram it has already recently retransmitted. How "recently" is determined by the configuration option source transport_lbtrm_ignore_interval (default 500ms). If this count is high, a receiver transport may be having trouble receiving retransmissions, or the ignore interval may be set too long. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of NAKs the source ignored and sent an NCF with reason code "ignored"
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksIgnored (int n) throws LBMException
Number of NAKs the source ignored and sent an NCF with reason code "ignored" (LBT-RM only). A source transport ignores a NAK for a datagram it has already recently retransmitted. How "recently" is determined by the configuration option source transport_lbtrm_ignore_interval (default 500ms). If this count is high, a receiver transport may be having trouble receiving retransmissions, or the ignore interval may be set too long. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of NAKs the source ignored and sent an NCF with reason code "ignored"
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksIgnoredRetransmitDelay () throws LBMException
Number of NAKs this source did not process because doing so would exceed its retransmit rate limit (LBT-RM only). This rate limit is set by configuration option transport_lbtrm_retransmit_rate_limit (default 5Mbps). For each of these NAKs, the source transport immediately sends an NFC rx_delay, then queues the retransmission for a later send within the rate limit. If this count is high, one or more crybaby receiver transports may be clogging the source transport's retransmit queue. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of NAKs this source transport has not processed because it met its retransmission rate limit
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksIgnoredRetransmitDelay (int n) throws LBMException
Number of NAKs this source did not process because doing so would exceed its retransmit rate limit (LBT-RM only). This rate limit is set by configuration option transport_lbtrm_retransmit_rate_limit (default 5Mbps). For each of these NAKs, the source transport immediately sends an NFC rx_delay, then queues the retransmission for a later send within the rate limit. If this count is high, one or more crybaby receiver transports may be clogging the source transport's retransmit queue. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of NAKs this source transport has not processed because it met its retransmission rate limit
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksReceived () throws LBMException
Number of individual NAKs received by the source transport (LBT-RM only). When a source transport receives a NAK from a receiver transport, it may respond by re-transmitting the requested LBT-RM datagram, or it may send an NCF. The NAKing receiver transport responds to the NCF by waiting (timeout set by transport_lbtrm_nak_suppress_interval, default 1000 ms), then re-sending the NAK. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of individual NAKs received by the source transport
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksReceived (int n) throws LBMException
Number of individual NAKs received by the source transport (LBT-RM only). When a source transport receives a NAK from a receiver transport, it may respond by re-transmitting the requested LBT-RM datagram, or it may send an NCF. The NAKing receiver transport responds to the NCF by waiting (timeout set by transport_lbtrm_nak_suppress_interval, default 1000 ms), then re-sending the NAK. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of individual NAKs received by the source transport
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksShed () throws LBMException
Number of NAKs this source shed and sent an NCF with reason code "shed" (LBT-RM only). When a source transport's retransmit rate limiter and retransmit queue are both at maximum, it responds to a NAK by sending an "NCF shed", and does not retransmit. The receiver transport should wait, then send another NAK. If this count is high, one or more crybaby receiver transports may be clogging the source transport's retransmit queue. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of NAKs this source shed and sent an NCF with reason code "shed"
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.naksShed (int n) throws LBMException
Number of NAKs this source shed and sent an NCF with reason code "shed" (LBT-RM only). When a source transport's retransmit rate limiter and retransmit queue are both at maximum, it responds to a NAK by sending an "NCF shed", and does not retransmit. The receiver transport should wait, then send another NAK. If this count is high, one or more crybaby receiver transports may be clogging the source transport's retransmit queue. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of NAKs this source shed and sent an NCF with reason code "shed"
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.numberOfClients () throws LBMException
Number of receiver clients currently connected over this transport (TCP only). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of receiver clients currently connected over this transport
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.numberOfClients (int n) throws LBMException
Number of receiver clients currently connected over this transport (TCP only). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of receiver clients currently connected over this transport
Exceptions
LBMException if any error occurred retrieving source statistics.
void com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.refresh (LBMContext lbmctx, int maxStats) throws LBMException
Refresh the aggregate set of statistics for a particular context. This method will throw LBMMonitorEInvalException if maxStats is less than the available number of transport statistical sets.
Parameters
lbmctx LBMContext object associated with statistics to be retrieved.
maxStats Maximum number of statistical sets to retrieve.
Exceptions
LBMException if any error occurred retrieving statistics.
Referenced by com.latencybusters.lbm.LBMContext.getImmediateMessageSourceStatistics(), and com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.LBMImmediateMessageSourceStatistics().
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.retransmissionBytesSent () throws LBMException
Total number of bytes retransmitted by this source transport (LBT-RM only). This count is triggered under the same circumstances as retransmissionsSent, above. In a normal, light-loss scenario, most NAKs received induce a retransmission. When losses become heavy and/or many receiver transports begin losing the same datagrams, NCF-related no-retransmit counts (naksIgnored, naksShed and naksIgnoredRetransmitDelay) may begin to inflate, and retransmissions retransmissionsSent) may become significantly lower than NAKs received (naksReceived). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of transport bytes retransmitted by this source
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.retransmissionBytesSent (int n) throws LBMException
Total number of bytes retransmitted by this source transport (LBT-RM only). This count is triggered under the same circumstances as retransmissionsSent, above. In a normal, light-loss scenario, most NAKs received induce a retransmission. When losses become heavy and/or many receiver transports begin losing the same datagrams, NCF-related no-retransmit counts (naksIgnored, naksShed and naksIgnoredRetransmitDelay) may begin to inflate, and retransmissions retransmissionsSent) may become significantly lower than NAKs received (naksReceived). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of transport bytes retransmitted by this source
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.retransmissionsQueued () throws LBMException
Number of retransmission datagrams currently queued by the retransmit rate limiter (LBT-RM only). When a source transport attempts to send retransmissions faster that its retransmit rate limiter allows (set by configuration option transport_lbtrm_retransmit_rate_limit, default 5Mbps), the retransmit rate limiter queues retransmissions until they can be sent within the rate limit. naks_rx_delay_ignored (above) will generally also rise if this count is high This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of datagrams currently queued by the retransmit rate limiter
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.retransmissionsQueued (int n) throws LBMException
Number of retransmission datagrams currently queued by the retransmit rate limiter (LBT-RM only). When a source transport attempts to send retransmissions faster that its retransmit rate limiter allows (set by configuration option transport_lbtrm_retransmit_rate_limit, default 5Mbps), the retransmit rate limiter queues retransmissions until they can be sent within the rate limit. naks_rx_delay_ignored (above) will generally also rise if this count is high This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of datagrams currently queued by the retransmit rate limiter
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.retransmissionsSent () throws LBMException
Number of datagrams retransmitted by this source transport (LBT-RM only). This count is incremented under the same circumstances as retransmissionBytesSent, below. In a normal, light-loss scenario, most NAKs received induce a retransmission. When losses become heavy and/or many receiver transports begin losing the same datagrams, NCF-related no-retransmit counts (naksIgnored, naksShed and naksIgnoredRetransmitDelay) may begin to inflate, and retransmissions retransmissionsSent) may become significantly lower than NAKS received (naksReceived). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of datagrams retransmitted by this source
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.retransmissionsSent (int n) throws LBMException
Number of datagrams retransmitted by this source transport (LBT-RM only). This count is incremented under the same circumstances as retransmissionBytesSent, below. In a normal, light-loss scenario, most NAKs received induce a retransmission. When losses become heavy and/or many receiver transports begin losing the same datagrams, NCF-related no-retransmit counts (naksIgnored, naksShed and naksIgnoredRetransmitDelay) may begin to inflate, and retransmissions retransmissionsSent) may become significantly lower than NAKS received (naksReceived). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of datagrams retransmitted by this source
Exceptions
LBMException if any error occurred retrieving source statistics.
int com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.size ()
Number of transport statistical sets encapsulated within this object
Returns
Statistical set size
String com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.source () throws LBMException
Source of transport as a string. The string format depends on transport type and is described under LBMTransportSourceInfo. This method returns a value from the first set of statistics encapsulated within this object
See also
LBMTransportSourceInfo
Returns
Source of transport as a string
Exceptions
LBMException if any error occurred retrieving statistics.
Referenced by com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.source().
String com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.source (int n) throws LBMException
Source of transport as a string. The string format depends on transport type and is described under LBMTransportSourceInfo. This method returns a value from the nth set of statistics encapsulated within this object.
See also
LBMTransportSourceInfo
Parameters
n Statistics set index
Returns
Source of transport as a string
Exceptions
LBMException if any error occurred retrieving receiver statistics.
References com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.source().
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.transmissionWindowBytes () throws LBMException
Number of bytes currently in the transmission window (LBT-RM only). Typically, this count approaches its window size or exceeds it by a small amount. See transmissionWindowMessages for a description of the transmission window. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of bytes currently in the transmission window
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.transmissionWindowBytes (int n) throws LBMException
Number of bytes currently in the transmission window (LBT-RM only). Typically, this count approaches its window size or exceeds it by a small amount. See transmissionWindowMessages for a description of the transmission window. This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of bytes currently in the transmission window
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.transmissionWindowMessages () throws LBMException
Number of datagrams in the transmission window (LBT-RM only). Each source transport session maintains a transmission window buffer (the size of which is set by transport_lbtrm_transmission_window_size, default 24MB). When the source transport receives a NAK, the corresponding message for retransmission must be found in this transmission window. This method returns a value from the first set of statistics encapsulated within this object.
Returns
Number of datagrams in the transmission window
Exceptions
LBMException if any error occurred retrieving source statistics.
long com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.transmissionWindowMessages (int n) throws LBMException
Number of datagrams in the transmission window (LBT-RM only). Each source transport session maintains a transmission window buffer (the size of which is set by transport_lbtrm_transmission_window_size, default 24MB). When the source transport receives a NAK, the corresponding message for retransmission must be found in this transmission window. This method returns a value from the first set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Number of datagrams in the transmission window
Exceptions
LBMException if any error occurred retrieving source statistics.
int com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.type () throws LBMException
Transport type (TCP, LBT-RM, etc.). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Transport type
Exceptions
LBMException if any error occurred retrieving receiver statistics.
See also
LBM
Referenced by com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.type().
int com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.type (int n) throws LBMException
Transport type (TCP, LBT-RM, etc.). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Transport type
Exceptions
LBMException if any error occurred retrieving receiver statistics.
See also
LBM
References com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.type().
String com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.typeName () throws LBMException
Transport type name (TCP, LBT-RM, etc.). This method returns a value from the first set of statistics encapsulated within this object.
Returns
Transport type name
Exceptions
LBMException if any error occurred retrieving statistics.
String com.latencybusters.lbm.LBMImmediateMessageSourceStatistics.typeName (int n) throws LBMException
Transport type name (TCP, LBT-RM, etc.). This method returns a value from the nth set of statistics encapsulated within this object.
Parameters
n Statistics set index
Returns
Transport type name
Exceptions
LBMException if any error occurred retrieving receiver statistics.
References com.latencybusters.lbm.LBM.TRANSPORT_STAT_LBTRM, and com.latencybusters.lbm.LBM.TRANSPORT_STAT_TCP.
The documentation for this class was generated from the following file:
LBMImmediateMessageSourceStatistics.java