UM Java API: com.latencybusters.lbm.UMEStoreGroupEntry Class Reference
com.latencybusters.lbm.UMEStoreGroupEntry Class Reference
Public Member Functions
UMEStoreGroupEntry ()
UMEStoreGroupEntry (int index, int groupSize) throws LBMEInvalException
int index ()
int groupSize ()
Detailed Description
UME Store Group Entry class. Holds information about a UME store group, like the group's index and group size.
Since
UME 2.0
Constructor & Destructor Documentation
com.latencybusters.lbm.UMEStoreGroupEntry.UMEStoreGroupEntry ()
Creates a UMEStoreGroupEntry object and initializes index and group size to 0.
Since
UME 2.0
com.latencybusters.lbm.UMEStoreGroupEntry.UMEStoreGroupEntry (int index, int groupSize) throws LBMEInvalException
Creates a UMEStoreGroupEntry object and initializes the index and group size.
Parameters
index Index of the store group (must be >= 0).
groupSize Size of the store group (must be >= 0).
Exceptions
LBMEInvalException if index or groupSize < 0.
Since
UME 2.0
References com.latencybusters.lbm.UMEStoreGroupEntry.groupSize(), and com.latencybusters.lbm.UMEStoreGroupEntry.index().
Member Function Documentation
int com.latencybusters.lbm.UMEStoreGroupEntry.groupSize ()
Returns this store group's size.
Returns
Group size.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMEStoreGroupEntry.UMEStoreGroupEntry().
int com.latencybusters.lbm.UMEStoreGroupEntry.index ()
Returns this store group's index.
Returns
The UME store group index.
Since
UME 2.0
Referenced by com.latencybusters.lbm.UMEStoreGroupEntry.UMEStoreGroupEntry().
The documentation for this class was generated from the following file:
UMEStoreGroupEntry.java