UM Java API: com.latencybusters.lbm.LBMTimespec Class Reference
com.latencybusters.lbm.LBMTimespec Class Reference
Public Member Functions
LBMTimespec ()
LBMTimespec (long tv_sec, long tv_nsec)
long tv_sec ()
long tv_nsec ()
Detailed Description
LBM Timespec class. Holds a time value in seconds and nanoseconds.
Since
UMMS 6.9
Constructor & Destructor Documentation
com.latencybusters.lbm.LBMTimespec.LBMTimespec ()
Creates an LBMTimespec object with all fields initialized to 0.
Since
UMS 6.9
com.latencybusters.lbm.LBMTimespec.LBMTimespec (long tv_sec, long tv_nsec)
Creates a LBMTimespec object with all fields initialized to the given values.
Parameters
tv_sec Holds a 64-bit value representing the seconds of the time value.
tv_nsec Holds a 64-bit value representing the nanoseconds of the time value.
Since
UMS 6.9
References com.latencybusters.lbm.LBMTimespec.tv_nsec(), and com.latencybusters.lbm.LBMTimespec.tv_sec().
Member Function Documentation
long com.latencybusters.lbm.LBMTimespec.tv_nsec ()
Get the nanoseconds associated with this time value.
Returns
nanoseconds associated with this time value.
Since
UMS 6.9
References com.latencybusters.lbm.LBMTimespec.tv_sec().
Referenced by com.latencybusters.lbm.LBMTimespec.LBMTimespec().
long com.latencybusters.lbm.LBMTimespec.tv_sec ()
Get the seconds associated with this time value.
Returns
seconds associated with this time value.
Since
UMS 6.9
Referenced by com.latencybusters.lbm.LBMTimespec.LBMTimespec(), and com.latencybusters.lbm.LBMTimespec.tv_nsec().
The documentation for this class was generated from the following file:
LBMTimespec.java