UM Java API: com.latencybusters.lbm.UMQQueueMessageStatus Class Reference
com.latencybusters.lbm.UMQQueueMessageStatus Class Reference
Public Member Functions
UMQMessageId queueMessageId ()
LBMMessage message ()
int status ()
int flags ()
Detailed Description
Class containing the current status of a UMQ message as reported by the queue daemon.
Member Function Documentation
int com.latencybusters.lbm.UMQQueueMessageStatus.flags ()
Get informational flags associated with the message in the queue; currently always returns 0.
Returns
the informational flags.
References com.latencybusters.lbm.LBMMessage.promote(), and com.latencybusters.lbm.UMQQueueMessageStatus.status().
LBMMessage com.latencybusters.lbm.UMQQueueMessageStatus.message ()
Gets the actual message data in the form of a normal LBMMessage object, if available. If not available, this will return null.
Returns
the LBMMessage object, if available; null otherwise.
UMQMessageId com.latencybusters.lbm.UMQQueueMessageStatus.queueMessageId ()
Gets the UMQ message ID of the message.
Returns
the UMQ message ID.
int com.latencybusters.lbm.UMQQueueMessageStatus.status ()
Get the status of the message within the queue, or LBM::UMQ_QUEUE_MSG_STATUS_UNKNOWN if the status is unavailable.
Returns
the message status.
See also
LBM::UMQ_QUEUE_MSG_STATUS_UNKNOWN
LBM::UMQ_QUEUE_MSG_STATUS_UNASSIGNED
LBM::UMQ_QUEUE_MSG_STATUS_ASSIGNED
LBM::UMQ_QUEUE_MSG_STATUS_REASSIGNING
LBM::UMQ_QUEUE_MSG_STATUS_CONSUMED
Referenced by com.latencybusters.lbm.UMQQueueMessageStatus.flags().
The documentation for this class was generated from the following file:
UMQQueueMessageStatus.java