UM Java API: com.latencybusters.lbm.UMQMessageTotalLifetimeInfo Class Reference
com.latencybusters.lbm.UMQMessageTotalLifetimeInfo Class Reference
Public Member Functions
UMQMessageTotalLifetimeInfo (long totalLifetime)
UMQMessageTotalLifetimeInfo ()
long totalLifetime ()
void setTotalLifetime (long totalLifetime)
Constructor & Destructor Documentation
com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.UMQMessageTotalLifetimeInfo (long totalLifetime)
Creates a UMQMessageTotalLifetimeInfo with the specified total lifetime
Parameters
totalLifetime Total lifetime of the message.
Since
UMQ 2.2
References com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.setTotalLifetime().
com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.UMQMessageTotalLifetimeInfo ()
Creates a UMQMessageTotalLifetimeInfo with the total lifetime set to 0
Since
UMQ 2.2
Member Function Documentation
void com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.setTotalLifetime (long totalLifetime)
Sets the total lifetime
Parameters
totalLifetime the new total lifetime
Since
UMQ 2.2
References com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.totalLifetime().
Referenced by com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.UMQMessageTotalLifetimeInfo().
long com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.totalLifetime ()
Returns the specified total lifetime
Since
UMQ 2.2
Referenced by com.latencybusters.lbm.UMQMessageTotalLifetimeInfo.setTotalLifetime().
The documentation for this class was generated from the following file:
UMQMessageTotalLifetimeInfo.java