UM .NET API: com.latencybusters.lbm.sdm.LBMSDMField Class Reference
com.latencybusters.lbm.sdm.LBMSDMField Class Reference
LBMSDMField is the base class for all LBM SDM field types. All base LBM SDM field types use the naming convention LBMSDMField(Type). Field arrays are subclasses of the respective field class and use the naming convention LBMSDMArray(Type). LBMSDMRaw(BaseType) is used as the naming convention for raw data types where needed and support the respective LBMSDMField(Type) classes.
Public Member Functions
virtual short getType ()
Get the type of this field.
System.String getTypeString ()
Get a string representing this field type.
virtual bool sameType (LBMSDMField f)
Compare the type of the field to this field.
virtual bool sameBaseType (LBMSDMField f)
Compare the base type of the field to this field.
virtual System.String get_name ()
Get the field name.
virtual void set_name (System.String new_name)
Set the name of this field. A copy of the name will be made.
LBMSDMField ()
Create an untyped, unnamed field.
virtual void set (LBMSDMField f, int arrayidx)
This is overridden by array classes.
virtual void add_element (LBMSDMField newfield)
Add an element to an array from a field.
virtual void append (LBMSDMField newfield)
This is overridden by array classes.
virtual System.String toDbgString ()
Create a string useful for debugging.
virtual System.String internalString (System.String sname, System.String sval)
Create a string based on the internal representation (includes the type)
virtual int get_len ()
This is overridden by field and array subclasses.
virtual int name_len ()
Get the length of this fields name in raw form. This is only needed by LBMSDMessage to format a raw message.
virtual int type_len ()
Get the length of the type field in raw form. This is only needed by LBMSDMessage to format a raw message.
virtual int format (byte[] buf, int offset)
This is overridden by field and array subclasses.
virtual int format_name (byte[] buf, int offset)
Format into a byte buffer the name of this field. Only needed by LBMSDMessage to format messages.
virtual int format_type (byte[] buf, int offset)
Format into a byte buffer the type of this field. Only needed by LBMSDMessage to format messages.
virtual int parse (byte[] buf, int offset)
This is overridden by field and array subclasses.
virtual new System.Object Clone ()
Clone this field.
virtual int length ()
Return the number of elements in an array.
virtual void remove (int element)
Remove an element from an array class.
virtual bool isNull ()
Test to see if this field is a null field (I.E. a field with no data)
virtual void setNull ()
Set this field to a null value - discarding current value (if any)
virtual void set_debug_level (int level)
Set the debug level for processing this SDM message. Currently all debugs go to standard out.
virtual void log (System.String s)
Log an event. If debug level is set greater than 0, output to stderr.
Static Public Member Functions
static short getType (System.String typeName, bool isarray)
Get the TYPE_XXX value for a given string. Recognised strings are: boolean, int8, uint8, int16, uint16, int32, uint32, int64, uint64, float, double, decimal, timestamp, message, string, unicode, blob.
Public Attributes
const int MAX_FIELD_NAME_LENGTH = 255
Maximum length of a field name.
const short TYPE_INVALID = 0
SDM field type: Type is invalid.
const short TYPE_BOOLEAN = 1
SDM field type: Boolean (non-zero is true; zero is false).
const short TYPE_INT8 = 2
SDM field type: 8-bit signed integer.
const short TYPE_UINT8 = 3
SDM field type: 8-bit unsigned integer.
const short TYPE_INT16 = 4
SDM field type: 16-bit signed integer.
const short TYPE_UINT16 = 5
SDM field type: 16-bit unsigned integer.
const short TYPE_INT32 = 6
SDM field type: 32-bit signed integer.
const short TYPE_UINT32 = 7
SDM field type: 32-bit unsigned integer.
const short TYPE_INT64 = 8
SDM field type: 64-bit signed integer.
const short TYPE_UINT64 = 9
SDM field type: 64-bit unsigned integer.
const short TYPE_FLOAT = 10
SDM field type: Single-precision floating point.
const short TYPE_DOUBLE = 11
SDM field type: Double-precision floating point.
const short TYPE_DECIMAL = 12
SDM field type: Decimal number.
const short TYPE_TIMESTAMP = 13
SDM field type: Seconds and microseconds since the epoch (UTC).
const short TYPE_MESSAGE = 14
SDM field type: Nested SDM message.
const short TYPE_STRING = 15
SDM field type: Character string (ASCIZ).
const short TYPE_UNICODE = 16
SDM field type: Unicode string.
const short TYPE_BLOB = 17
SDM field type: Binary Large Object (BLOB).
const short TYPE_ARRAY_BOOLEAN = TYPE_BOOLEAN | TYPE_MODIFIER_ARRAY
SDM field type: Array of Booleans (non-zero is true; zero is false).
const short TYPE_ARRAY_INT8 = TYPE_INT8 | TYPE_MODIFIER_ARRAY
SDM field type: Array of 8-bit signed integers.
const short TYPE_ARRAY_UINT8 = (short) ((TYPE_UINT8 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 8-bit unsigned integers.
const short TYPE_ARRAY_INT16 = (short) ((TYPE_INT16 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 16-bit signed integers.
const short TYPE_ARRAY_UINT16 = (short) ((TYPE_UINT16 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 16-bit unsigned integers.
const short TYPE_ARRAY_INT32 = (short) ((TYPE_INT32 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 32-bit signed integers.
const short TYPE_ARRAY_UINT32 = (short) ((TYPE_UINT32 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 32-bit unsigned integers.
const short TYPE_ARRAY_INT64 = (short) ((TYPE_INT64 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 64-bit signed integers.
const short TYPE_ARRAY_UINT64 = (short) ((TYPE_UINT64 | TYPE_MODIFIER_ARRAY))
SDM field type: Array of 64-bit unsigned integers.
const short TYPE_ARRAY_FLOAT = (short) ((TYPE_FLOAT | TYPE_MODIFIER_ARRAY))
SDM field type: Array of single-precision floating points.
const short TYPE_ARRAY_DOUBLE = (short) ((TYPE_DOUBLE | TYPE_MODIFIER_ARRAY))
SDM field type: Array of double-precision floating points.
const short TYPE_ARRAY_DECIMAL = (short) ((TYPE_DECIMAL | TYPE_MODIFIER_ARRAY))
SDM field type: Array of decimal numbers.
const short TYPE_ARRAY_TIMESTAMP = (short) ((TYPE_TIMESTAMP | TYPE_MODIFIER_ARRAY))
SDM field type: Array of timestamps (seconds and microseconds since the epoch (UTC)).
const short TYPE_ARRAY_MESSAGE = (short) ((TYPE_MESSAGE | TYPE_MODIFIER_ARRAY))
SDM field type: Array of nested SDM messages.
const short TYPE_ARRAY_STRING = (short) ((TYPE_STRING | TYPE_MODIFIER_ARRAY))
SDM field type: Array of character strings (ASCIZ).
const short TYPE_ARRAY_UNICODE = (short) ((TYPE_UNICODE | TYPE_MODIFIER_ARRAY))
SDM field type: Array of unicode strings.
const short TYPE_ARRAY_BLOB = (short) ((TYPE_BLOB | TYPE_MODIFIER_ARRAY))
SDM field type: Array of Binary Large Objects (BLOB).
const int DEBUG_BASIC = 1
Debug flag for basic debug output.
const int DEBUG_VERBOSE_PARSING = 2
Debug flag for verbose message parsing output.
Properties
virtual System.String TypeString [get]
Get a string representing this field type.
Detailed Description
LBMSDMField is the base class for all LBM SDM field types. All base LBM SDM field types use the naming convention LBMSDMField(Type). Field arrays are subclasses of the respective field class and use the naming convention LBMSDMArray(Type). LBMSDMRaw(BaseType) is used as the naming convention for raw data types where needed and support the respective LBMSDMField(Type) classes.
Member Function Documentation
virtual void com.latencybusters.lbm.sdm.LBMSDMField.add_element (LBMSDMField newfield) virtual
Add an element to an array from a field.
Parameters
newfield The new field to be added
Referenced by com.latencybusters.lbm.sdm.LBMSDMFieldIterator.add_element().
virtual void com.latencybusters.lbm.sdm.LBMSDMField.append (LBMSDMField newfield) virtual
This is overridden by array classes.
LBMSDMException when a non array field tries to call append()
Parameters
newfield The new field to be appended
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, and com.latencybusters.lbm.sdm.LBMSDMArrayBool.
virtual new System.Object com.latencybusters.lbm.sdm.LBMSDMField.Clone () virtual
Clone this field.
Returns
A new field that is a copy of this object
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMFieldString, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, com.latencybusters.lbm.sdm.LBMSDMArrayBool, com.latencybusters.lbm.sdm.LBMSDMFieldUnicode, com.latencybusters.lbm.sdm.LBMSDMFieldBlob, com.latencybusters.lbm.sdm.LBMSDMFieldUint64, com.latencybusters.lbm.sdm.LBMSDMFieldMessage, com.latencybusters.lbm.sdm.LBMSDMFieldUint32, com.latencybusters.lbm.sdm.LBMSDMFieldDecimal, com.latencybusters.lbm.sdm.LBMSDMFieldUint16, com.latencybusters.lbm.sdm.LBMSDMFieldUint8, com.latencybusters.lbm.sdm.LBMSDMFieldInt32, com.latencybusters.lbm.sdm.LBMSDMFieldInt16, com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp, com.latencybusters.lbm.sdm.LBMSDMFieldInt8, com.latencybusters.lbm.sdm.LBMSDMFieldInt64, com.latencybusters.lbm.sdm.LBMSDMFieldBool, and com.latencybusters.lbm.sdm.LBMSDMFieldFloat.
References com.latencybusters.lbm.sdm.LBMSDMField.Clone(), com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_BLOB, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_BOOLEAN, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_DECIMAL, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_DOUBLE, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_FLOAT, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_INT16, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_INT32, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_INT64, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_INT8, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_MESSAGE, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_STRING, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_TIMESTAMP, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_UINT16, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_UINT32, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_UINT64, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_UINT8, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_ARRAY_UNICODE, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_BLOB, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_BOOLEAN, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_DECIMAL, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_DOUBLE, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_FLOAT, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_INT16, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_INT32, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_INT64, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_INT8, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_MESSAGE, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_STRING, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_TIMESTAMP, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_UINT16, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_UINT32, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_UINT64, com.latencybusters.lbm.sdm.LBMSDMField.TYPE_UINT8, and com.latencybusters.lbm.sdm.LBMSDMField.TYPE_UNICODE.
Referenced by com.latencybusters.lbm.sdm.LBMSDMField.Clone().
virtual int com.latencybusters.lbm.sdm.LBMSDMField.format (byte[] buf, int offset) virtual
This is overridden by field and array subclasses.
LBMSDMException when an unexpected error occurs within LBMSDM
Parameters
buf The buffer to format the message in to
offset The offset in to the byte buffer
Returns
-1
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, com.latencybusters.lbm.sdm.LBMSDMArrayBool, com.latencybusters.lbm.sdm.LBMSDMFieldString, com.latencybusters.lbm.sdm.LBMSDMFieldBlob, com.latencybusters.lbm.sdm.LBMSDMFieldUint64, com.latencybusters.lbm.sdm.LBMSDMFieldUnicode, com.latencybusters.lbm.sdm.LBMSDMFieldDecimal, com.latencybusters.lbm.sdm.LBMSDMFieldMessage, com.latencybusters.lbm.sdm.LBMSDMFieldUint32, com.latencybusters.lbm.sdm.LBMSDMFieldUint8, com.latencybusters.lbm.sdm.LBMSDMFieldUint16, com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp, com.latencybusters.lbm.sdm.LBMSDMFieldDouble, com.latencybusters.lbm.sdm.LBMSDMFieldInt32, com.latencybusters.lbm.sdm.LBMSDMFieldInt16, com.latencybusters.lbm.sdm.LBMSDMFieldInt8, com.latencybusters.lbm.sdm.LBMSDMFieldFloat, com.latencybusters.lbm.sdm.LBMSDMFieldBool, and com.latencybusters.lbm.sdm.LBMSDMFieldInt64.
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data().
virtual int com.latencybusters.lbm.sdm.LBMSDMField.format_name (byte[] buf, int offset) virtual
Format into a byte buffer the name of this field. Only needed by LBMSDMessage to format messages.
LBMSDMException when an unexpected error occurs within LBMSDM
Parameters
buf The buffer to format the message in to
offset The offset in to the byte buffer where the message should be placed
Returns
The new offset in the buffer after formatting the message name
References com.latencybusters.lbm.sdm.LBMSDMFieldString.format_short().
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data().
virtual int com.latencybusters.lbm.sdm.LBMSDMField.format_type (byte[] buf, int offset) virtual
Format into a byte buffer the type of this field. Only needed by LBMSDMessage to format messages.
LBMSDMException when an unexpected error occurs within LBMSDM
Parameters
buf The buffer to format the type in to
offset The offset in to the byte buffer where the type should be placed
Returns
The new offset in the buffer after formatting the message type
References com.latencybusters.lbm.sdm.LBMSDMRawUint16.format(), and com.latencybusters.lbm.sdm.LBMSDMRawUint16.length.
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data().
virtual int com.latencybusters.lbm.sdm.LBMSDMField.get_len () virtual
This is overridden by field and array subclasses.
Returns
0
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayBool, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp, com.latencybusters.lbm.sdm.LBMSDMFieldDecimal, com.latencybusters.lbm.sdm.LBMSDMFieldDouble, com.latencybusters.lbm.sdm.LBMSDMFieldFloat, com.latencybusters.lbm.sdm.LBMSDMFieldInt16, com.latencybusters.lbm.sdm.LBMSDMFieldInt32, com.latencybusters.lbm.sdm.LBMSDMFieldInt64, com.latencybusters.lbm.sdm.LBMSDMFieldUint32, com.latencybusters.lbm.sdm.LBMSDMFieldUint8, com.latencybusters.lbm.sdm.LBMSDMFieldInt8, com.latencybusters.lbm.sdm.LBMSDMFieldUint16, com.latencybusters.lbm.sdm.LBMSDMFieldBlob, com.latencybusters.lbm.sdm.LBMSDMFieldBool, com.latencybusters.lbm.sdm.LBMSDMFieldMessage, com.latencybusters.lbm.sdm.LBMSDMFieldString, com.latencybusters.lbm.sdm.LBMSDMFieldUnicode, and com.latencybusters.lbm.sdm.LBMSDMFieldUint64.
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data().
virtual System.String com.latencybusters.lbm.sdm.LBMSDMField.get_name () virtual
Get the field name.
Returns
A string containing the field name
Referenced by com.latencybusters.lbm.sdm.LBMSDMFields.add(), com.latencybusters.lbm.sdm.LBMSDMessage.data(), com.latencybusters.lbm.sdm.LBMSDMFields.locate(), and com.latencybusters.lbm.sdm.LBMSDMFields.set().
static short com.latencybusters.lbm.sdm.LBMSDMField.getType (System.String typeName, bool isarray) static
Get the TYPE_XXX value for a given string. Recognised strings are: boolean, int8, uint8, int16, uint16, int32, uint32, int64, uint64, float, double, decimal, timestamp, message, string, unicode, blob.
Parameters
typeName A string which needs translating to a short form
isarray A boolean indicating if an array type is required
Returns
A short representation for the string or TYPE_INVALID
virtual short com.latencybusters.lbm.sdm.LBMSDMField.getType () virtual
Get the type of this field.
Returns
The TYPE_XXX value of this object
System.String com.latencybusters.lbm.sdm.LBMSDMField.getTypeString ()
Get a string representing this field type.
Returns
A string representing this field type
virtual System.String com.latencybusters.lbm.sdm.LBMSDMField.internalString (System.String sname, System.String sval) virtual
Create a string based on the internal representation (includes the type)
Parameters
sname The field name
sval The field value in string form
Returns
A string that contains the field name and value in ascii form
virtual bool com.latencybusters.lbm.sdm.LBMSDMField.isNull () virtual
Test to see if this field is a null field (I.E. a field with no data)
Returns
true/false
virtual int com.latencybusters.lbm.sdm.LBMSDMField.length () virtual
Return the number of elements in an array.
LBMSDMNotArrayException if called for non array classes
Returns
The number of elements
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, and com.latencybusters.lbm.sdm.LBMSDMArrayBool.
virtual void com.latencybusters.lbm.sdm.LBMSDM.log (System.String s) virtual inherited
Log an event. If debug level is set greater than 0, output to stderr.
Parameters
s String containing the event to log
virtual int com.latencybusters.lbm.sdm.LBMSDMField.name_len () virtual
Get the length of this fields name in raw form. This is only needed by LBMSDMessage to format a raw message.
Returns
the number of bytes the name of this field needs plus one for the length
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data().
virtual int com.latencybusters.lbm.sdm.LBMSDMField.parse (byte[] buf, int offset) virtual
This is overridden by field and array subclasses.
LBMSDMException parse() should be overridden
Parameters
buf The buffer to format in to
offset The offset in to the byte buffer
Returns
nothing - always throws exception
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMFieldString, com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, com.latencybusters.lbm.sdm.LBMSDMArrayBool, com.latencybusters.lbm.sdm.LBMSDMFieldUint64, com.latencybusters.lbm.sdm.LBMSDMFieldUnicode, com.latencybusters.lbm.sdm.LBMSDMFieldBlob, com.latencybusters.lbm.sdm.LBMSDMFieldDecimal, com.latencybusters.lbm.sdm.LBMSDMFieldMessage, com.latencybusters.lbm.sdm.LBMSDMFieldUint32, com.latencybusters.lbm.sdm.LBMSDMFieldUint16, com.latencybusters.lbm.sdm.LBMSDMFieldUint8, com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp, com.latencybusters.lbm.sdm.LBMSDMFieldDouble, com.latencybusters.lbm.sdm.LBMSDMFieldInt32, com.latencybusters.lbm.sdm.LBMSDMFieldInt16, com.latencybusters.lbm.sdm.LBMSDMFieldInt8, com.latencybusters.lbm.sdm.LBMSDMFieldFloat, com.latencybusters.lbm.sdm.LBMSDMFieldInt64, and com.latencybusters.lbm.sdm.LBMSDMFieldBool.
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.parse().
virtual void com.latencybusters.lbm.sdm.LBMSDMField.remove (int element) virtual
Remove an element from an array class.
Parameters
element The array element to be removed
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayBool, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, and com.latencybusters.lbm.sdm.LBMSDMArrayUint16.
virtual bool com.latencybusters.lbm.sdm.LBMSDMField.sameBaseType (LBMSDMField f) virtual
Compare the base type of the field to this field.
Parameters
f A field to compare
Returns
true if the same type, false if not
virtual bool com.latencybusters.lbm.sdm.LBMSDMField.sameType (LBMSDMField f) virtual
Compare the type of the field to this field.
Parameters
f A field to compare
Returns
true if the same type, false if not
virtual void com.latencybusters.lbm.sdm.LBMSDMField.set (LBMSDMField f, int arrayidx) virtual
This is overridden by array classes.
Parameters
f The array field to be modified
arrayidx The array index of the field to be set
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, and com.latencybusters.lbm.sdm.LBMSDMArrayBool.
Referenced by com.latencybusters.lbm.sdm.LBMSDMFields.set().
virtual void com.latencybusters.lbm.sdm.LBMSDM.set_debug_level (int level) virtual inherited
Set the debug level for processing this SDM message. Currently all debugs go to standard out.
Parameters
level Debug level to set
virtual void com.latencybusters.lbm.sdm.LBMSDMField.set_name (System.String new_name) virtual
Set the name of this field. A copy of the name will be made.
Parameters
new_name The name this field shall use.
virtual System.String com.latencybusters.lbm.sdm.LBMSDMField.toDbgString () virtual
Create a string useful for debugging.
Returns
A string that contains the field in a form useful for debugging
Reimplemented in com.latencybusters.lbm.sdm.LBMSDMArrayMessage, com.latencybusters.lbm.sdm.LBMSDMArrayUnicode, com.latencybusters.lbm.sdm.LBMSDMArrayDecimal, com.latencybusters.lbm.sdm.LBMSDMArrayUint64, com.latencybusters.lbm.sdm.LBMSDMArrayBlob, com.latencybusters.lbm.sdm.LBMSDMArrayString, com.latencybusters.lbm.sdm.LBMSDMArrayTimestamp, com.latencybusters.lbm.sdm.LBMSDMArrayDouble, com.latencybusters.lbm.sdm.LBMSDMArrayFloat, com.latencybusters.lbm.sdm.LBMSDMArrayInt16, com.latencybusters.lbm.sdm.LBMSDMArrayInt32, com.latencybusters.lbm.sdm.LBMSDMArrayInt64, com.latencybusters.lbm.sdm.LBMSDMArrayInt8, com.latencybusters.lbm.sdm.LBMSDMArrayUint32, com.latencybusters.lbm.sdm.LBMSDMArrayUint8, com.latencybusters.lbm.sdm.LBMSDMArrayUint16, com.latencybusters.lbm.sdm.LBMSDMArrayBool, com.latencybusters.lbm.sdm.LBMSDMFieldDecimal, com.latencybusters.lbm.sdm.LBMSDMFieldUint64, com.latencybusters.lbm.sdm.LBMSDMFieldBlob, com.latencybusters.lbm.sdm.LBMSDMFieldTimestamp, com.latencybusters.lbm.sdm.LBMSDMFieldMessage, com.latencybusters.lbm.sdm.LBMSDMFieldUnicode, com.latencybusters.lbm.sdm.LBMSDMFieldUint32, com.latencybusters.lbm.sdm.LBMSDMFieldUint8, com.latencybusters.lbm.sdm.LBMSDMFieldUint16, com.latencybusters.lbm.sdm.LBMSDMFieldDouble, com.latencybusters.lbm.sdm.LBMSDMFieldFloat, com.latencybusters.lbm.sdm.LBMSDMFieldInt16, com.latencybusters.lbm.sdm.LBMSDMFieldInt32, com.latencybusters.lbm.sdm.LBMSDMFieldInt64, com.latencybusters.lbm.sdm.LBMSDMFieldInt8, com.latencybusters.lbm.sdm.LBMSDMFieldString, and com.latencybusters.lbm.sdm.LBMSDMFieldBool.
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.parse(), and com.latencybusters.lbm.sdm.LBMSDMFields.toDbgString().
virtual int com.latencybusters.lbm.sdm.LBMSDMField.type_len () virtual
Get the length of the type field in raw form. This is only needed by LBMSDMessage to format a raw message.
Returns
the number of bytes the type field needs
References com.latencybusters.lbm.sdm.LBMSDMFieldUint16.fixed_size().
Referenced by com.latencybusters.lbm.sdm.LBMSDMessage.data().
Property Documentation
virtual System.String com.latencybusters.lbm.sdm.LBMSDMField.TypeString get
Get a string representing this field type.
Values: A string representing this field type
Returns
A string representing this field type
The documentation for this class was generated from the following file:
LBMSDMField.cs