UM .NET API: com.latencybusters.pdm.PDMSegmentHeader Class Reference
com.latencybusters.pdm.PDMSegmentHeader Class Reference
The chained segment header is the internal PDM header class used by the different PDM segments of a message. It includes a next header type as well as the length of its corresponding segment.
Public Member Functions
virtual void clear ()
Clears the header so it can be reused without creating a new one.
virtual byte[] toBytes (PDMSerializer ser)
Serializes this object to a new byte array.
virtual int toBytes (PDMSerializer ser, byte[] ba, int pos)
Serializes this object to an existing byte array at position.
virtual int parse (PDMDeserializer deser, byte[] ba, int pos)
Parses the byte array at position into this object.
Properties
virtual sbyte NextHeaderType [get, set]
virtual short Reserved [get, set]
virtual sbyte Flags [get, set]
virtual int SectionLength [get, set]
virtual bool Flag0 [get]
virtual bool Flag1 [get]
virtual bool Flag2 [get]
virtual bool Flag3 [get]
virtual bool Flag4 [get]
virtual bool Flag5 [get]
virtual bool Flag6 [get]
virtual bool IgnoreBit [get]
Detailed Description
The chained segment header is the internal PDM header class used by the different PDM segments of a message. It includes a next header type as well as the length of its corresponding segment.
Member Function Documentation
virtual int com.latencybusters.pdm.PDMSegmentHeader.parse (PDMDeserializer deser, byte[] ba, int pos) virtual
Parses the byte array at position into this object.
Returns
the updated position in the byte array after parsing this object
References com.latencybusters.pdm.PDMDeserializer.readByte(), com.latencybusters.pdm.PDMDeserializer.readInt(), and com.latencybusters.pdm.PDMDeserializer.readShort().
Referenced by com.latencybusters.pdm.PDMMessage.getFields().
virtual byte [] com.latencybusters.pdm.PDMSegmentHeader.toBytes (PDMSerializer ser) virtual
Serializes this object to a new byte array.
Returns
the new byte array
Referenced by com.latencybusters.pdm.PDMMessage.getFields().
virtual int com.latencybusters.pdm.PDMSegmentHeader.toBytes (PDMSerializer ser, byte[] ba, int pos) virtual
Serializes this object to an existing byte array at position.
Returns
the updated position in the byte array after serializing this object
References com.latencybusters.pdm.PDMSerializer.writeByte(), com.latencybusters.pdm.PDMSerializer.writeInt(), and com.latencybusters.pdm.PDMSerializer.writeShort().
The documentation for this class was generated from the following file:
PDMSegmentHeader.cs