UM .NET API: com.latencybusters.lbm.sdm.LBMSDMRawDouble Class Reference
com.latencybusters.lbm.sdm.LBMSDMRawDouble Class Reference
An LBMSDMRawDouble is a helper class to minimise the effort of formatting and parsing Doubles.
Public Member Functions
virtual void set (double v)
Set the raw double from a double field.
LBMSDMRawDouble ()
Create a raw double object, setting the value to 0.
LBMSDMRawDouble (double v)
Create a raw double object providing the value.
virtual int format (byte[] buf, int offset)
Format the raw double value into a byte buffer.
override System.String ToString ()
Get a string representing the raw double value.
virtual int parse (byte[] buf, int offset)
Parse the raw double value from a byte buffer The value is stored in the object.
virtual double toDouble ()
Get the double value of this raw double.
virtual System.String toDbgString ()
Get a debug string for this object. This is not expected to be called and exists for child classes.
virtual void set_debug_level (int level)
Set the debug level for processing this SDM message. Currently all debugs go to standard out.
virtual void log (System.String s)
Log an event. If debug level is set greater than 0, output to stderr.
System.Object Clone ()
Get a copy of this object.
Static Public Member Functions
static int format (byte[] buf, int offset, double v)
Format a double value into a byte buffer.
static double parse_s (byte[] buf, int offset)
Parse the raw double value from a byte buffer.
Public Attributes
const int DEBUG_BASIC = 1
Debug flag for basic debug output.
const int DEBUG_VERBOSE_PARSING = 2
Debug flag for verbose message parsing output.
Static Public Attributes
static int length = 8
The length of a raw double.
Detailed Description
An LBMSDMRawDouble is a helper class to minimise the effort of formatting and parsing Doubles.
Constructor & Destructor Documentation
com.latencybusters.lbm.sdm.LBMSDMRawDouble.LBMSDMRawDouble (double v)
Create a raw double object providing the value.
Parameters
v The value of the raw double
Member Function Documentation
System.Object com.latencybusters.lbm.sdm.LBMSDM.Clone () inherited
Get a copy of this object.
Returns
A new object with a copy
static int com.latencybusters.lbm.sdm.LBMSDMRawDouble.format (byte[] buf, int offset, double v) static
Format a double value into a byte buffer.
Parameters
buf The buffer to contain the formatted value
offset The offset in to the buffer to start formatting
v The value of the double to be formatted
Returns
The offset after formatting the double
Referenced by com.latencybusters.lbm.sdm.LBMSDMFieldDouble.toDbgString().
virtual int com.latencybusters.lbm.sdm.LBMSDMRawDouble.format (byte[] buf, int offset) virtual
Format the raw double value into a byte buffer.
Parameters
buf The buffer to contain the formatted value
offset The offset in to the buffer to start formatting
Returns
The offset after formatting this object
virtual void com.latencybusters.lbm.sdm.LBMSDM.log (System.String s) virtual inherited
Log an event. If debug level is set greater than 0, output to stderr.
Parameters
s String containing the event to log
virtual int com.latencybusters.lbm.sdm.LBMSDMRawDouble.parse (byte[] buf, int offset) virtual
Parse the raw double value from a byte buffer The value is stored in the object.
Parameters
buf The buffer that contains the formatted value
offset The offset in to the buffer to start parsing
Returns
the new offset after parsing the field
static double com.latencybusters.lbm.sdm.LBMSDMRawDouble.parse_s (byte[] buf, int offset) static
Parse the raw double value from a byte buffer.
Parameters
buf The buffer that contains the formatted value
offset The offset in to the buffer to start parsing
Returns
The double value parsed
References com.latencybusters.lbm.sdm.LBMSDMRawUint64.parse_s().
Referenced by com.latencybusters.lbm.sdm.LBMSDMFieldDouble.parse().
virtual void com.latencybusters.lbm.sdm.LBMSDMRawDouble.set (double v) virtual
Set the raw double from a double field.
Parameters
v The value the raw double needs to be set to
virtual void com.latencybusters.lbm.sdm.LBMSDM.set_debug_level (int level) virtual inherited
Set the debug level for processing this SDM message. Currently all debugs go to standard out.
Parameters
level Debug level to set
virtual System.String com.latencybusters.lbm.sdm.LBMSDMRaw.toDbgString () virtual inherited
Get a debug string for this object. This is not expected to be called and exists for child classes.
Returns
returns null - derived classes override with their value
Referenced by com.latencybusters.lbm.sdm.LBMSDMBadRawObjectException.LBMSDMBadRawObjectException().
virtual double com.latencybusters.lbm.sdm.LBMSDMRawDouble.toDouble () virtual
Get the double value of this raw double.
Returns
The double value of this object
override System.String com.latencybusters.lbm.sdm.LBMSDMRawDouble.ToString ()
Get a string representing the raw double value.
Returns
A string representing the raw double value
The documentation for this class was generated from the following file:
LBMSDMRawDouble.cs