UM .NET API: com.latencybusters.lbm.LBMHFXAttributes Class Reference
com.latencybusters.lbm.LBMHFXAttributes Class Reference
Encapsulates the set of default LBM HFX attributes.
Public Member Functions
unsafe LBMHFXAttributes ()
Instantiate LBMHFXAttributes class.
unsafe LBMHFXAttributes (string topicName)
Instantiate an LBMHFXAttributes class using a topic name from the xml configuration that must have been previously loaded.
void Dispose ()
Free memory associated with this set of attributes.
void dispose ()
Free memory associated with this set of attributes (same as Dispose()).
unsafe void setFromXml (string topicName)
Set values in an LBMHFXAttributes class using a topic name from the xml configuration that must have been previously loaded.
unsafe List< LBMConfigOption > dumpAttributeList ()
Dump HFX configuration options.
unsafe string getValue (string attributeName)
Returns the current value of an attribute from this set of HFX attributes.
unsafe void setValue (string attributeName, string attributeValue)
Set the current value of an attribute in this set of HFX attributes.
void setObjectRecycler (LBMObjectRecyclerBase objRec, Object objRecCbArg)
Set the LBM object recycler that can be used by the context to reuse LBMMessage objects as well as LBM Context/Receiver/Source Statistics objects.
Detailed Description
Encapsulates the set of default LBM HFX attributes.
Constructor & Destructor Documentation
unsafe com.latencybusters.lbm.LBMHFXAttributes.LBMHFXAttributes ()
Instantiate LBMHFXAttributes class.
Exceptions
com.latencybusters.lbm.LBMException Invalid argument or unexpected operational behavior has been encountered by unmanaged LBM C layer function.
unsafe com.latencybusters.lbm.LBMHFXAttributes.LBMHFXAttributes (string topicName)
Instantiate an LBMHFXAttributes class using a topic name from the xml configuration that must have been previously loaded.
Parameters
topicName The topic name string that will be used to create the LBMHFX object.
Exceptions
com.latencybusters.lbm.LBMException The HFX topic name is not permitted by XML configuration or other unexpected operational behavior has been encountered by unmanaged LBM C layer function.
References com.latencybusters.lbm.LBM.errorMessage(), and com.latencybusters.lbm.LBM.errorNumber().
Member Function Documentation
void com.latencybusters.lbm.LBMHFXAttributes.dispose ()
Free memory associated with this set of attributes (same as Dispose()).
See also
Dispose
References com.latencybusters.lbm.LBM.errorMessage(), and com.latencybusters.lbm.LBM.errorNumber().
unsafe List<LBMConfigOption> com.latencybusters.lbm.LBMHFXAttributes.dumpAttributeList ()
Dump HFX configuration options.
Exceptions
com.latencybusters.lbm.LBMException Invalid argument or unexpected operational behavior has been encountered by unmanaged LBM C layer function.
Returns
An array of LBMConfigOptions
References com.latencybusters.lbm.LBM.errorMessage(), com.latencybusters.lbm.LBM.errorNumber(), com.latencybusters.lbm.LBMConfigOption.OptionName, com.latencybusters.lbm.LBMConfigOption.Type, and com.latencybusters.lbm.LBMConfigOption.Value.
unsafe string com.latencybusters.lbm.LBMHFXAttributes.getValue (string attributeName)
Returns the current value of an attribute from this set of HFX attributes.
Parameters
attributeName Name of the attribute to retrieve
Exceptions
com.latencybusters.lbm.LBMException Invalid argument or unexpected operational behavior has been encountered by unmanaged LBM C layer function.
Returns
Value corresponding to the specified attribute name
References com.latencybusters.lbm.LBM.errorMessage(), and com.latencybusters.lbm.LBM.errorNumber().
unsafe void com.latencybusters.lbm.LBMHFXAttributes.setFromXml (string topicName)
Set values in an LBMHFXAttributes class using a topic name from the xml configuration that must have been previously loaded.
Parameters
topicName The topic name string that will be used to create the LBMHFX object.
Exceptions
com.latencybusters.lbm.LBMException The HFX topic name is not permitted by XML configuration or other unexpected operational behavior has been encountered by unmanaged LBM C layer function.
References com.latencybusters.lbm.LBM.errorMessage(), and com.latencybusters.lbm.LBM.errorNumber().
void com.latencybusters.lbm.LBMHFXAttributes.setObjectRecycler (LBMObjectRecyclerBase objRec, Object objRecCbArg)
Set the LBM object recycler that can be used by the context to reuse LBMMessage objects as well as LBM Context/Receiver/Source Statistics objects.
Parameters
objRec an LBM object recycler that will be called when objects need to be retrieved
objRecCbArg a callback object token that will be passed in the retrieve method
unsafe void com.latencybusters.lbm.LBMHFXAttributes.setValue (string attributeName, string attributeValue)
Set the current value of an attribute in this set of HFX attributes.
Parameters
attributeName Name of the attribute to set
attributeValue New attribute value
Exceptions
com.latencybusters.lbm.LBMException Invalid argument or unexpected operational behavior has been encountered by unmanaged LBM C layer function.
References com.latencybusters.lbm.LBM.errorMessage(), and com.latencybusters.lbm.LBM.errorNumber().
The documentation for this class was generated from the following file:
LBMHFXAttributes.cs