UM .NET API: com.latencybusters.lbm Namespace Reference
com.latencybusters.lbm Namespace Reference
Main classes for the Ultra Messaging API.
Namespaces
namespace sdm
Main classes for the Ultra Messaging Self-Describing Messages API.
Classes
class CallbackInfo
Summary description for CallbackInfo.
class CallConvCdeclAttribute
class JMSMessageId
JMSMessageID class. This object creates a JMS MessageId.
class LBM
LBM Utility class.
struct lbm_context_event_umq_registration_complete_ex_t
struct lbm_context_event_umq_registration_ex_t
struct lbm_hf_rcv_t
struct lbm_hfx_rcv_t
struct lbm_hfx_t
struct lbm_lbtsmx_transport_info_t
struct lbm_msg_properties_data_t
struct lbm_msg_properties_header_t
struct lbm_msg_properties_index_t
struct lbm_msg_properties_t
Structure passed in via lbm_source_send_ex_info_t.
struct lbm_process_events_info_t
struct lbm_rcv_t
struct lbm_rcv_transport_stats_lbtsmx_t
struct lbm_src_send_ex_info_t
struct lbm_src_transport_stats_lbtsmx_t
struct lbm_transport_lbtsmx_ctlr_t
struct lbm_umq_msgid_t
struct LBMConfigOption
LBM Option class.
class LBMContext
Creates an LBM context.
class LBMContextAttributes
Encapsulates the set of default LBM context attributes.
class LBMContextEvent
Encapsulates LBM Context Events.
class LBMContextSourceEvent
Encapsulates an LBM context-level source event.
class LBMContextSourceEventObjectDisposer
class LBMContextSourceEventObjectFactory
class LBMContextStatistics
LBM Context Statistics.
class LBMContextStatisticsObjectDisposer
class LBMContextStatisticsObjectFactory
class LBMDeliveryController
class LBMEInvalException
LBM Invalid value exception class.
class LBMEMessageSelectorException
LBM message selector exception class.
class LBMENoMemException
LBM memory allocation exception class.
class LBMEOPException
LBM internal processing exception class.
class LBMEOSException
LBM unrecoverable OS system call exception class.
class LBMETimedOutException
LBM timed out operation exception class.
class LBMEventQueue
LBM Event Queue class. This class may be subclassed to override the default event queue monitoring method or an LBMEventQueueCallback interface may be specified to handle the monitor callback.
class LBMEventQueueAttributes
Encapsulates the set of default LBM event queue attributes.
class LBMEventQueueStatistics
UM event queue statistics. These are statistics for messages and other events that enter and exit the event queue. NOTE: Specific count-enable options must sometimes be enabled for these statistics to populate.
class LBMEventQueueStatisticsObjectDisposer
class LBMEventQueueStatisticsObjectFactory
class LBMEWouldBlockException
LBM blocked operation exception class (occurs when a function that would otherwise block is set to be nonblocking)
class LBMException
Base LBM Exception class.
class LBMFlightSize
class LBMGenericCallbackInfo
Internal class used for callback info objects that uses generics to avoid the casting that is needed when using the normal CallbackInfo class.
class LBMGenericObjectPool
class LBMHFX
Creates an LBM HFX object.
class LBMHFXAttributes
Encapsulates the set of default LBM HFX attributes.
class LBMHFXReceiver
The LBMHFXReceiver object is used to associate an LBMHFX object with an LBMContext. Messages are delivered by each LBMHFXReceiver to the LBMHFX object, which handles dropping duplicates and ordering messages.
class LBMHotFailoverReceiver
LBM Hot-Failover Receiver class.
class LBMHotFailoverSource
LBM Hot-Failover Source class.
class LBMImmediateMessageReceiverStatistics
UM Receiver Transport Statistics.
class LBMImmediateMessageReceiverStatisticsObjectDisposer
class LBMImmediateMessageReceiverStatisticsObjectFactory
class LBMImmediateMessageSourceStatistics
UM context immediate message source transport statistics.
class LBMImmediateMessageSourceStatisticsObjectDisposer
class LBMImmediateMessageSourceStatisticsObjectFactory
class LBMLbtSmxTransport
Encapsulates an SMX transport, inherited by both source and receiver transport.
class LBMLbtSmxTransportController
class LBMLbtSmxTransportReceiver
class LBMLbtSmxTransportReceiverDemux
class LBMLbtSmxTransportReceiverDemuxBucket
class LBMLbtSmxTransportReceiverDemuxBucketEntry
class LBMLbtSmxTransportSource
class LBMMessage
class LBMMessageChannelInfo
Encapsulates information about channel data send with a message.
class LBMMessageObjectDisposer
class LBMMessageObjectFactory
class LBMMessageProperties
Represents a collection of properties contained in an LBMMessage object.
class LBMMessageProperty
Represents a key-value pair included with an LBMMessage object.
class LBMMonitor
LBM Monitor class.
class LBMMonitorEAgainException
LBM Monitor insufficient resources exception class.
class LBMMonitorEAlreadyException
LBM Monitor resource already registered exception class.
class LBMMonitorEInvalException
LBM Monitor invalid value exception class.
class LBMMonitorELBMFailException
LBM Monitor LBM failure exception class.
class LBMMonitorEModFailException
LBM Monitor module function failure exception class.
class LBMMonitorENoMemException
LBM Monitor out-of-memory exception class.
class LBMMonitorReceiver
LBM Monitor Receiver class.
class LBMMonitorSource
LBM Monitor Source class.
interface LBMObjectDisposer
interface LBMObjectFactory
class LBMObjectRecycler
Basic implementation of an object recycler that implements all supported LBM object types. The size limits for the object pools for each object type can be tuned and should be set immediately after instantiating the class and before using any instance of the class. This implementation is synchronized on a per object type basis(doneWithMessage/retrieveMessage, doneWithReceiverStatistics/retrieveReceiverStatistics, etc) via a thread local pool of objects and a synchronized shared pool of objects.
class LBMObjectRecyclerBase
class LBMOperationCompleteCallback
LBMOperationCompleteCallback class.
class LBMReceiver
LBM Receiver class.
class LBMReceiverAttributes
Encapsulates the set of default LBM receiver attributes.
class LBMReceiverStatistics
LBM Receiver Transport Statistics.
class LBMReceiverStatisticsObjectDisposer
class LBMReceiverStatisticsObjectFactory
class LBMRequest
LBM Request class.
class LBMResolverEvent
LBMResolverEvent.
class LBMResolverEventAdvertisement
class LBMSetInflightInfo
Class used to wrap the provided user callback and cbObj into the client data for the C call.
class LBMSource
LBM Source class.
class LBMSourceAttributes
Encapsulates the set of default LBM source attributes.
class LBMSourceChannelInfo
LBM Source Channel Info class.
class LBMSourceEvent
Encapsulates LBM Source Events.
class LBMSourceEventFlightSizeNotification
LBM Source Event Flight Size Notification class. Contains type and state of current flight size.
class LBMSourceEventObjectDisposer
class LBMSourceEventObjectFactory
class LBMSourceEventSequenceNumberInfo
LBM Source Event Sequence Number Info class.
class LBMSourceEventWakeupInfo
Class containing information about a source wakeup event.
class LBMSourceSendExInfo
LBM Source Send Extended Info class.
class LBMSourceStatistics
LBM Source Transport Statistics.
class LBMSourceStatisticsObjectDisposer
class LBMSourceStatisticsObjectFactory
class LBMStatistics
UM Transport Statistics base class.
class LBMTimer
LBM Timer class.
class LBMTLContainer
struct lbmtmgr_dctlr_entry_t
struct lbmtmgr_hfx_rcv_t
struct lbmtmgr_hfx_t
struct lbmtmgr_rcv_entry_t
struct lbmtmgr_topic_entry_t
class LBMTopic
LBM Topic class. It is recommended that topic objects be instantiated from the context factory methods allocTopic() and lookupTopic() (for sources and receivers respectively).
class LBMTransportSourceInfo
Class that is passed to the source cost callback with source transport information.
class LBMUMMInfo
LBM UMM options class.
class LBMWildcardReceiver
LBM Wildcard Receiver class.
class LBMWildcardReceiverAttributes
Encapsulates the set of default LBM wildcard receiver attributes.
struct lbtsmx_basic_hdr_t
struct lbtsmx_cntl_callback_hdr_t
struct lbtsmx_cntl_exit_hdr_t
struct lbtsmx_cntl_lbm_rcv_t_add_hdr_t
struct lbtsmx_cntl_lbm_rcv_t_del_hdr_t
struct lbtsmx_cntl_rcv_add_hdr_t
struct lbtsmx_cntl_rcv_remove_hdr_t
struct lbtsmx_dummy_hdr_t
class LBTSMX_HDR_TYPE
struct lbtsmx_msg_hdr_t
struct lbtsmx_rcv_opts_t
struct lbtsmx_rcv_t
struct lbtsmx_session_id_t
struct lbtsmx_src_opts_t
struct lbtsmx_transport_rcv_t
struct lbtsmx_transport_src_rcvr_list_entry_t
struct lbtsmx_transport_src_t
struct lbtsmx_txw_buff_info_t
struct lbtsmx_txw_rcvr_node_t
struct lbtsmx_txw_sh_header_t
struct lbtsmx_txw_t
class MulArraySet
struct src_event_cbobj_handles_t
struct timeval
class UMEDeregistrationCompleteInfo
UME Deregistration Complete Info class.
class UMEDeregistrationSuccessInfo
UME Deregistration Success Info class.
class UMEMessageAck
UMEMessageAck class. Use this object to send explicit acks.
class UMENoQueueException
UME registration incomplete exception class.
class UMENoRegException
UME registration incomplete exception class.
class UMENoStoreException
UME registration incomplete exception class.
class UMEReceiverLivenessCallbackInfo
Class that is passed to the receiver liveness creation and deletion callback with receiver information.
class UMERecoverySequenceNumberCallbackInfo
UME Recovery sequence number callback info class.
class UMERegistrationCompleteInfo
UME Registration Complete Info class.
class UMERegistrationIdExCallbackInfo
UME Registration ID Extended Callback Info class.
class UMERegistrationSuccessInfo
UME Registration Success Info class.
class UMESourceEventAckInfo
UME Source Event Ack Info class.
class UMESourceEventDeregistrationCompleteInfo
UME Source Event Deregistration Complete Info class.
class UMESourceEventDeregistrationSuccessInfo
UME Source Event Deregistration Success Info class.
class UMESourceEventRegistrationCompleteInfo
UME Source Event Registration Complete Info class.
class UMESourceEventRegistrationSuccessInfo
UME Source Event Registration Success Info class.
class UMEStoreEntry
UME Store Entry class.
class UMEStoreGroupEntry
UME Store Group Entry class.
class UMQContextEventRegistrationCompleteInfo
Class containing information about UMQ Registration Complete Context Events. This info object is delivered with a UMQ Registration Complete Context Event, containing information identifying the queue and registration id associated with the registration complete event.
class UMQContextEventRegistrationSuccessInfo
Class containing information about UMQ Registration Success Context Events. This info object is delivered with a UMQ Registration Success Context Event, containing information identifying the queue, queue instance, and registration id associated with the registration success event.
class UMQDeregistrationCompleteInfo
UMQ Deregistration Complete Info class. Contains extended information for UMQ receiver deregistration complete messages. This info object is supplied with a message indicating the a receiver has successfully deregistered with a queue.
class UMQIndexAssignedInfo
Class containing information about UMQ index assignment events. This info object is delivered with a UMQ Index Assigned receiver event, containing information identifying the queue, queue instance, and index information associated with the index assigned event.
class UMQIndexAssignmentEligibilityStartCompleteInfo
UMQ Index Assignment Eligibility Start Complete Info class. Contains extended information for UMQ receiver index assignment eligibility start complete messages. This info object is supplied with a message indicating the a receiver is now eligible for new index assignments from a queue.
class UMQIndexAssignmentEligibilityStopCompleteInfo
UMQ Index Assignment Eligibility Stop Complete Info class. Contains extended information for UMQ receiver index assignment eligibility stop complete messages. This info object is supplied with a message indicating the a receiver is now no longer eligible for new index assignments from a queue.
class UMQIndexInfo
UMQIndexInfo class.
class UMQIndexReleasedInfo
Class containing information about UMQ index released events. This info object is delivered with a UMQ Index Released receiver event, containing information identifying the queue, queue instance, and index information associated with the index released event.
class UMQMessageId
UMQ Message ID class. Contains information required to identify a UMQ message.
class UMQMessageTotalLifetimeInfo
UMQMessageTotalLifetimeInfo class.
class UMQQueueIndexInfo
UMQQueueIndexInfo class.
class UMQQueueInfo
Base class for UMQ info objects associated with a queue. This class encapsulates the basic information required for any UMQ info object that is associated with a queue, namely the identifying information for the queue (Id and Name) and a set of flags to indicate other information contained in the object.
class UMQQueueInstanceInfo
Base class for UMQ info objects associated with a queue instance. This class encapsulates the information required for any UMQ info object that is associated with a queue instance. This includes both the information required to identify the queue (Id and Name) as well as the information needed to identify the queue instance (Index and Name).
class UMQRegistrationCompleteInfo
UMQ Registration Complete Info class. Contains extended information for UMQ receiver registration complete messages.
class UMQSourceEventAckInfo
UMQ Stability Ack Info class. This info object is delivered with a source event indicating that a message is stable (i.e. has been acknowledged by a queue instance).
class UMQSourceEventMessageIdInfo
This class encapsulates information about a message sent to a queue. An object of type UMQSourceEventMessageIdInfo will be delivered with a source event of type LBM.SRC_EVENT_UMQ_MESSAGE_ID_INFO to notify the application of the message id that has been assigned to the message by the queue.
class UMQSourceEventRegistrationCompleteInfo
UMQ Source Event Registration Complete Info class. This info object is delivered with a source event indicating that registration is complete to all involved queue instances.
class UMQSourceEventULBMessageInfo
UMQ ULB Message Info class. This info object is delivered with a source event indicating that a ULB message has been assigned, consumed, discarded, etc.
class UMQSourceEventULBReceiverInfo
UMQ ULB Receiver Info class. This info object is both delivered with a source event and acts as a base class for other ULB source events. In both cases, this object holds information about a ULB receiver.
Typedefs
using size_t = System.Int32
Functions
delegate void LBMLogging (int level, string message)
LBM logging callback delegate.
delegate int LBMImmediateMessageCallback (object cbArg, LBMMessage lbmmsg)
Received immediate message callback delegate.
delegate void LBMContextSourceEventCallback (object cbArg, LBMContextSourceEvent sourceEvent)
Context source event callback delegate.
delegate void LBMSourceNotification (string topic, string source, object cbArg)
New source notification callback delegate.
delegate int LBMContextEventCallback (object cbArg, LBMContextEvent contextEvent)
Context event callback.
delegate int LBMResolverEventCallback (object cbArg, LBMResolverEvent resolverEvent)
Resolver event callback.
delegate uint LBMSourceCostCallback (object cbArg, string topic, LBMTransportSourceInfo transport, uint hop_count, uint cost)
Application callback to evaluate the cost of a newly discovered source. Set via the context attributes setSourceCostCallback function.
delegate object UMEReceiverLivenessCreationCallback (UMEReceiverLivenessCallbackInfo info, object cbArg)
Application callback to attain information about a new "connected" receiver.
delegate int UMEReceiverLivenessDeletionCallback (UMEReceiverLivenessCallbackInfo info, object cbArg, object srcCbArg)
Application callback to attain information about a previously "connected" receiver that has gone away.
delegate void LBMEventQueueCallback (object cbArg, int eventType, int eventQueueSize, long eventQueueDelay)
Event queue callback delegate.
delegate int LBMSetInflightCallback (int inflight, object cbArg)
Callback for setting the inflight messages for a source.
delegate void LBMSetInflightCallbackEx (ref int messages, ref ulong bytes, object cbArg)
Callback for setting the number of inflight messages and bytes for a source simultaneously.
delegate int DeliverMessageCallback (LBMMessage msg)
delegate void LBMMonitorReceiverStatisticsCallback (LBMReceiverStatistics lbmrcvstats)
Received receiver statistics callback delegate.
delegate void LBMMonitorSourceStatisticsCallback (LBMSourceStatistics lbmsrcstats)
Received source statistics callback delegate.
delegate void LBMMonitorEventQueueStatisticsCallback (LBMEventQueueStatistics lbmevqstats)
Received event queue statistics callback delegate.
delegate void LBMMonitorContextStatisticsCallback (LBMContextStatistics lbmctxstats)
Received context statistics callback delegate.
delegate void LBMMonitorImmediateMessageSourceStatisticsCallback (LBMImmediateMessageSourceStatistics lbmimsrcstats)
Received immediate message source statistics callback delegate.
delegate void LBMMonitorImmediateMessageReceiverStatisticsCallback (LBMImmediateMessageReceiverStatistics lbmimrcvstats)
Received immediate message receiver statistics callback delegate.
delegate int LBMReceiverCallback (object cbArg, LBMMessage lbmmsg)
Received message callback delegate.
delegate long LBMRegistrationIdCallback (object cbArg, string source, long sourceRegId)
Receiver registration ID callback delegate (UME only)
delegate uint UMERegistrationIdExCallback (object cbArg, UMERegistrationIdExCallbackInfo cbInfo)
Receiver registration ID callback delegate, extended version (UME only)
delegate int UMERecoverySequenceNumberCallback (object cbArg, UMERecoverySequenceNumberCallbackInfo cbInfo)
Receiver recovery sequence number callback delegate.
delegate object LBMSourceCreationCallback (string sourceName, object cbArg)
Application callback for notification of creation of sources for a topic.
delegate object LBMReceiverCreationCallback (string receiverName, object cbArg)
Application callback for notification of creation of a receiver for a topic.
delegate int LBMSourceDeletionCallback (string sourceName, object cbArg, object sourceCbArg)
Application callback for notification of deletion of sources for a topic.
delegate int LBMResponseCallback (object cbArg, LBMRequest lbmreq, LBMMessage lbmmsg)
Request response callback delegate.
delegate void LBMSourceEventCallback (object cbArg, LBMSourceEvent sourceEvent)
Source event callback delegate.
delegate void LBMMessageReclamationCallback (object cbArg, string topic, long seqnum)
Forced message reclamation callback delegate (UME only).
delegate void LBMTimerCallback (object cbArg)
LBM Timer callback delegate.
delegate int LBMWildcardPatternCallback (string topic, object cbArg)
LBM wildcard pattern match callback delegate.
delegate int LBMWildcardReceiverCreateCallback (string topic, LBMReceiverAttributes attr, object cbArg)
LBM wildcard receiver create callback delegate.
delegate int LBMWildcardReceiverDeleteCallback (string topic, object cbArg)
LBM wildcard receiver delete callback delegate.
Detailed Description
Main classes for the Ultra Messaging API.
Function Documentation
delegate int com.latencybusters.lbm.LBMContextEventCallback (object cbArg, LBMContextEvent contextEvent)
Context event callback.
Parameters
cbArg Callback object token
contextEvent LBMContextEvent object encapsulating event
Returns
an int, which should always be 0.
Referenced by com.latencybusters.lbm.LBMContextAttributes.disableSourceNotification().
delegate void com.latencybusters.lbm.LBMContextSourceEventCallback (object cbArg, LBMContextSourceEvent sourceEvent)
Context source event callback delegate.
Parameters
cbArg Callback object token
sourceEvent LBMContextSourceEvent object encapsulating context source event information
Referenced by com.latencybusters.lbm.LBMContextAttributes.disableSourceNotification().
delegate void com.latencybusters.lbm.LBMEventQueueCallback (object cbArg, int eventType, int eventQueueSize, long eventQueueDelay)
Event queue callback delegate.
Parameters
cbArg Callback object token
eventType Type of event
eventQueueSize Current queue size (number of messages)
eventQueueDelay Queuing delay (in microseconds) associated with the first message on the event queue
Referenced by com.latencybusters.lbm.LBMEventQueue.removeMonitor(), and com.latencybusters.lbm.LBMEventQueue.resetStatistics().
delegate int com.latencybusters.lbm.LBMImmediateMessageCallback (object cbArg, LBMMessage lbmmsg)
Received immediate message callback delegate.
Parameters
cbArg Callback object token
lbmmsg LBMMessage object encapsulating the received message
Returns
-1 indicates that the message could not be received and should be redelivered. (Note: if multiple callbacks are registered, a -1 return from any callback will cause the message to be redelivered to all the callbacks.)
Referenced by com.latencybusters.lbm.LBMContext.allocTopic(), com.latencybusters.lbm.LBMContextAttributes.disableSourceNotification(), and com.latencybusters.lbm.LBMContext.removeImmediateMessageReceiver().
delegate void com.latencybusters.lbm.LBMLogging (int level, string message)
LBM logging callback delegate.
Parameters
level Logging level, where values can be (in order of decreasing importance):
LBM.LOG_EMERG
LBM.LOG_ALERT
LBM.LOG_CRIT
LBM.LOG_ERR
LBM.LOG_WARNING
LBM.LOG_NOTICE
LBM.LOG_INFO
LBM.LOG_DEBUG
message Log message
delegate void com.latencybusters.lbm.LBMMessageReclamationCallback (object cbArg, string topic, long seqnum)
Forced message reclamation callback delegate (UME only).
This callback is invoked when retained UME source messages are forcibly reclaimed.
Parameters
cbArg Callback object token
topic Name of the topic for the reclaimed message
seqnum Sequence number of the message that is reclaimed
Referenced by com.latencybusters.lbm.LBMSourceAttributes.setMessageReclamationCallback().
delegate void com.latencybusters.lbm.LBMMonitorContextStatisticsCallback (LBMContextStatistics lbmctxstats)
Received context statistics callback delegate.
Parameters
lbmctxstats LBMContextStatistics object encapsulating the received context statistics
Referenced by com.latencybusters.lbm.LBMMonitorReceiver.removeStatisticsCallback().
delegate void com.latencybusters.lbm.LBMMonitorEventQueueStatisticsCallback (LBMEventQueueStatistics lbmevqstats)
Received event queue statistics callback delegate.
Parameters
lbmevqstats LBMEventQueueStatistics object encapsulating the received event queue statistics
Referenced by com.latencybusters.lbm.LBMMonitorReceiver.removeStatisticsCallback().
delegate void com.latencybusters.lbm.LBMMonitorImmediateMessageReceiverStatisticsCallback (LBMImmediateMessageReceiverStatistics lbmimrcvstats)
Received immediate message receiver statistics callback delegate.
Parameters
lbmimrcvstats LBMImmediateMessageReceiverStatistics object encapsulating the received immediate message receiver statistics.
Referenced by com.latencybusters.lbm.LBMMonitorReceiver.removeStatisticsCallback().
delegate void com.latencybusters.lbm.LBMMonitorImmediateMessageSourceStatisticsCallback (LBMImmediateMessageSourceStatistics lbmimsrcstats)
Received immediate message source statistics callback delegate.
Parameters
lbmimsrcstats LBMImmediateMessageSourceStatistics object encapsulating the received immediate message source statistics.
Referenced by com.latencybusters.lbm.LBMMonitorReceiver.removeStatisticsCallback().
delegate void com.latencybusters.lbm.LBMMonitorReceiverStatisticsCallback (LBMReceiverStatistics lbmrcvstats)
Received receiver statistics callback delegate.
Parameters
lbmrcvstats LBMReceiverStatistics object encapsulating the received receiver statistics
Referenced by com.latencybusters.lbm.LBMMonitorReceiver.removeStatisticsCallback().
delegate void com.latencybusters.lbm.LBMMonitorSourceStatisticsCallback (LBMSourceStatistics lbmsrcstats)
Received source statistics callback delegate.
Parameters
lbmsrcstats LBMSourceStatistics object encapsulating the received source statistics
Referenced by com.latencybusters.lbm.LBMMonitorReceiver.removeStatisticsCallback().
delegate int com.latencybusters.lbm.LBMReceiverCallback (object cbArg, LBMMessage lbmmsg)
Received message callback delegate.
Parameters
cbArg Callback object token
lbmmsg LBMMessage object encapsulating the received message
Returns
all return values are ignored
Referenced by com.latencybusters.lbm.LBMReceiver.LBMReceiver(), com.latencybusters.lbm.LBMReceiver.removeReceiver(), and com.latencybusters.lbm.LBMWildcardReceiver.removeReceiver().
delegate object com.latencybusters.lbm.LBMReceiverCreationCallback (string receiverName, object cbArg)
Application callback for notification of creation of a receiver for a topic.
Parameters
receiverName The unique receiver name string (e.g., "TCP:192.168.0.4:45789").
cbArg Callback object token.
Returns
User-supplied callback object to pass in to corresponding LBMSourceDeletionCallback callback.
delegate long com.latencybusters.lbm.LBMRegistrationIdCallback (object cbArg, string source, long sourceRegId)
Receiver registration ID callback delegate (UME only)
Parameters
cbArg Callback object token
source Name of the source for the ID
sourceRegId Registration ID for the source
Returns
Registration ID to be used by the receiver
Referenced by com.latencybusters.lbm.LBMReceiverAttributes.LBMReceiverAttributes().
delegate int com.latencybusters.lbm.LBMResolverEventCallback (object cbArg, LBMResolverEvent resolverEvent)
Resolver event callback.
Parameters
cbArg Callback object token
resolverEvent LBMResolverEvent object encapsulating event
Returns
an int, which should always be 0.
Referenced by com.latencybusters.lbm.LBMContextAttributes.disableSourceNotification().
delegate int com.latencybusters.lbm.LBMResponseCallback (object cbArg, LBMRequest lbmreq, LBMMessage lbmmsg)
Request response callback delegate.
Parameters
cbArg Callback object token
lbmreq LBMRequest object corresponding to the original request
lbmmsg LBMMessage object encapsulating the received message response
Returns
-1 indicates that the response could not be received and should be redelivered. (Note: if multiple callbacks are registered, a -1 return from any callback will cause the message to be redelivered to all the callbacks.)
Referenced by com.latencybusters.lbm.LBMRequest.removeResponseCallback().
delegate int com.latencybusters.lbm.LBMSetInflightCallback (int inflight, object cbArg)
Callback for setting the inflight messages for a source.
Parameters
inflight Current inflight value
cbArg Callback object specified with setXXXInflight
Returns
New inflight value
delegate void com.latencybusters.lbm.LBMSetInflightCallbackEx (ref int messages, ref ulong bytes, object cbArg)
Callback for setting the number of inflight messages and bytes for a source simultaneously.
Parameters
messages The current value of inflight messages, set to a new value to change
bytes The current value of inflight bytes, set to a new value to change
cbArg Callback object specified with setInflight
delegate uint com.latencybusters.lbm.LBMSourceCostCallback (object cbArg, string topic, LBMTransportSourceInfo transport, uint hop_count, uint cost)
Application callback to evaluate the cost of a newly discovered source. Set via the context attributes setSourceCostCallback function.
Parameters
cbArg Callback object token
topic Topic for which the new source was discovered
transport LBMTransportSourceInfo object describing the transport session
hop_count Current hop count for the transport session
cost Current cumulative cost for the transport session
Returns
Application-determined cost for this source as an unsigned 32-bit number. To permanently reject this source, return LBM.LBM_SRC_COST_FUNCTION_REJECT
Referenced by com.latencybusters.lbm.LBMContextAttributes.disableSourceNotification().
delegate object com.latencybusters.lbm.LBMSourceCreationCallback (string sourceName, object cbArg)
Application callback for notification of creation of sources for a topic.
Parameters
sourceName The unique source name string (e.g., "TCP:192.168.0.4:45789").
cbArg Callback object token.
Returns
User-supplied callback object to pass in to corresponding LBMSourceDeletionCallback callback.
Referenced by com.latencybusters.lbm.LBMTopic.LBMTopic().
delegate int com.latencybusters.lbm.LBMSourceDeletionCallback (string sourceName, object cbArg, object sourceCbArg)
Application callback for notification of deletion of sources for a topic.
Parameters
sourceName The unique source name string (e.g., "TCP:192.168.0.4:45789").
cbArg Callback object token.
sourceCbArg Callback object token returned by the corresponding LBMSourceCreationCallback.
Referenced by com.latencybusters.lbm.LBMTopic.LBMTopic().
delegate void com.latencybusters.lbm.LBMSourceEventCallback (object cbArg, LBMSourceEvent sourceEvent)
Source event callback delegate.
Parameters
cbArg Callback object token
sourceEvent LBMSourceEvent object encapsulating source event information
Referenced by com.latencybusters.lbm.LBMHotFailoverSource.LBMHotFailoverSource(), com.latencybusters.lbm.LBMSource.LBMSource(), and com.latencybusters.lbm.LBMSource.removeSourceCallback().
delegate void com.latencybusters.lbm.LBMSourceNotification (string topic, string source, object cbArg)
New source notification callback delegate.
Parameters
topic Topic string for available
source String identifing source advertising on this topic
cbArg Callback object token
Referenced by com.latencybusters.lbm.LBMContextAttributes.disableSourceNotification(), com.latencybusters.lbm.LBMContext.LBMContext(), and com.latencybusters.lbm.LBMContext.removeSourceNotifyCallback().
delegate void com.latencybusters.lbm.LBMTimerCallback (object cbArg)
LBM Timer callback delegate.
Parameters
cbArg Callback object token
Referenced by com.latencybusters.lbm.LBMTimer.removeTimerCallback(), and com.latencybusters.lbm.LBMTimer.reschedule().
delegate int com.latencybusters.lbm.LBMWildcardPatternCallback (string topic, object cbArg)
LBM wildcard pattern match callback delegate.
Parameters
topic Candidate topic string
cbArg Callback object token
Returns
0 indicates a match
Referenced by com.latencybusters.lbm.LBMWildcardReceiverAttributes.setPatternCallback().
delegate int com.latencybusters.lbm.LBMWildcardReceiverCreateCallback (string topic, LBMReceiverAttributes attr, object cbArg)
LBM wildcard receiver create callback delegate.
Parameters
topic Receiver topic string
attr Receiver attributes
cbArg Callback object token
Returns
0 indicates a match
Referenced by com.latencybusters.lbm.LBMWildcardReceiverAttributes.setReceiverDeleteCallback().
delegate int com.latencybusters.lbm.LBMWildcardReceiverDeleteCallback (string topic, object cbArg)
LBM wildcard receiver delete callback delegate.
Parameters
topic Receiver topic string
cbArg Callback object token
Returns
Always 0
Referenced by com.latencybusters.lbm.LBMWildcardReceiverAttributes.setReceiverDeleteCallback().
delegate object com.latencybusters.lbm.UMEReceiverLivenessCreationCallback (UMEReceiverLivenessCallbackInfo info, object cbArg)
Application callback to attain information about a new "connected" receiver.
Parameters
info Information about the receiver whom has been declared "alive"
cbArg Callback object token
Returns
User-supplied callback object passed in to corresponding UMEReceiverLivenessDeletionCallback callback.
Referenced by com.latencybusters.lbm.LBMContext.removeSourceNotifyCallback().
delegate int com.latencybusters.lbm.UMEReceiverLivenessDeletionCallback (UMEReceiverLivenessCallbackInfo info, object cbArg, object srcCbArg)
Application callback to attain information about a previously "connected" receiver that has gone away.
Parameters
info Information about the receiver whom has been declared "dead"
cbArg Callback object token
srcCbArg Callback object token returned by the corresponding UMEReceiverLivenessCreationCallback.
Referenced by com.latencybusters.lbm.LBMContext.removeSourceNotifyCallback().
delegate int com.latencybusters.lbm.UMERecoverySequenceNumberCallback (object cbArg, UMERecoverySequenceNumberCallbackInfo cbInfo)
Receiver recovery sequence number callback delegate.
Sets the lowest sequence number to be requested during recovery.
Parameters
cbArg Callback object token.
cbInfo Recovery sequence number info. See UMERecoverySequenceNumberCallbackInfo
Returns
This callback should always return 0. The lowest requested sequence number should be set, if desired, by UMERecoverySequenceNumberCallbackInfo.setLowSequenceNumber before returning.
Referenced by com.latencybusters.lbm.LBMReceiverAttributes.LBMReceiverAttributes().
delegate uint com.latencybusters.lbm.UMERegistrationIdExCallback (object cbArg, UMERegistrationIdExCallbackInfo cbInfo)
Receiver registration ID callback delegate, extended version (UME only)
Parameters
cbArg Callback object token
cbInfo Registration ID callback info; see UMERegistrationIdExCallbackInfo
Returns
Registration ID to be used by the receiver.
Referenced by com.latencybusters.lbm.LBMReceiverAttributes.LBMReceiverAttributes().